### PR TITLE
Add dataset export facility

### PR DESCRIPTION
**Pull request by zhiltsov-max**
Added:
- Dataset building and export for tasks
- REST API methods: `/api/v1/tasks/<id>/export[?format=][action=download]`

Current design:
Added the subproject `Datumaro`, responsible for dataset manipulations, such as building compound datasets, format conversions, filtering/merging etc. Currently supported scenario is similar to `CVAT`'s `export annotation`, however it is extended by direct dataset building, which includes images and annotations.

How to test:
- Create a task, obtain its `id`
- Call `/api/v1/tasks/<id>/export?format=<format>`
- Call `/api/v1/tasks/<id>/export?format=<format>&action=download`

Currently available formats can be found [here](https://github.com/opencv/cvat/blob/zm/datumaro-integration/cvat/apps/datumaro/dependencies/datumaro/datumaro/components/converters/__init__.py). Additionally, there is an option to export a Datumaro project to be operated on locally. It essentially requires Datumaro to be available locally.

Implementation:
- Exports are cached on the server for [some time](https://github.com/opencv/cvat/blob/zm/datumaro-integration/cvat/apps/datumaro/task.py#L136). Be aware that this functionality can heavily increase server storage consumption.

Related: #791 
Related: https://github.com/opencv/cvat/projects/15

### CODE REVIEW

**Comment by nmanovic** [comment]
@zhiltsov-max ,

<details>
$ docker exec -it cvat /bin/bash -c 'python3 manage.py test cvat/apps/engine utils/cli'

5388Creating test database for alias 'default'...
5389Getting flipped tasks...
5390Conversion started...
5391Destroying test database for alias 'default'...
5392Traceback (most recent call last):
5393  File "manage.py", line 21, in <module>
5394    execute_from_command_line(sys.argv)
5395  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
5396    utility.execute()
5397  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 375, in execute
5398    self.fetch_command(subcommand).run_from_argv(self.argv)
5399  File "/usr/local/lib/python3.5/dist-packages/django/core/management/commands/test.py", line 23, in run_from_argv
5400    super().run_from_argv(argv)
5401  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 323, in run_from_argv
5402    self.execute(*args, **cmd_options)
5403  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 364, in execute
5404    output = self.handle(*args, **options)
5405  File "/usr/local/lib/python3.5/dist-packages/django/core/management/commands/test.py", line 53, in handle
5406    failures = test_runner.run_tests(test_labels)
5407  File "/usr/local/lib/python3.5/dist-packages/django/test/runner.py", line 632, in run_tests
5408    self.run_checks()
5409  File "/usr/local/lib/python3.5/dist-packages/django/test/runner.py", line 570, in run_checks
5410    call_command('check', verbosity=self.verbosity)
5411  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 148, in call_command
5412    return command.execute(*args, **defaults)
5413  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 364, in execute
5414    output = self.handle(*args, **options)
5415  File "/usr/local/lib/python3.5/dist-packages/django/core/management/commands/check.py", line 64, in handle
5416    fail_level=getattr(checks, options['fail_level']),
5417  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 390, in check
5418    include_deployment_checks=include_deployment_checks,
5419  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 377, in _run_checks
5420    return checks.run_checks(**kwargs)
5421  File "/usr/local/lib/python3.5/dist-packages/django/core/checks/registry.py", line 72, in run_checks
5422    new_errors = check(app_configs=app_configs)
5423  File "/usr/local/lib/python3.5/dist-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
5424    all_namespaces = _load_all_namespaces(resolver)
5425  File "/usr/local/lib/python3.5/dist-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
5426    url_patterns = getattr(resolver, 'url_patterns', [])
5427  File "/usr/local/lib/python3.5/dist-packages/django/utils/functional.py", line 80, in __get__
5428    res = instance.__dict__[self.name] = self.func(instance)
5429  File "/usr/local/lib/python3.5/dist-packages/django/urls/resolvers.py", line 579, in url_patterns
5430    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
5431  File "/usr/local/lib/python3.5/dist-packages/django/utils/functional.py", line 80, in __get__
5432    res = instance.__dict__[self.name] = self.func(instance)
5433  File "/usr/local/lib/python3.5/dist-packages/django/urls/resolvers.py", line 572, in urlconf_module
5434    return import_module(self.urlconf_name)
5435  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
5436    return _bootstrap._gcd_import(name[level:], package, level)
5437  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
5438  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
5439  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
5440  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
5441  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
5442  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
5443  File "/home/django/cvat/urls.py", line 30, in <module>
5444    path('', include('cvat.apps.engine.urls')),
5445  File "/usr/local/lib/python3.5/dist-packages/django/urls/conf.py", line 34, in include
5446    urlconf_module = import_module(urlconf_module)
5447  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
5448    return _bootstrap._gcd_import(name[level:], package, level)
5449  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
5450  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
5451  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
5452  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
5453  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
5454  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
5455  File "/home/django/cvat/apps/engine/urls.py", line 7, in <module>
5456    from . import views
5457  File "/home/django/cvat/apps/engine/views.py", line 50, in <module>
5458    import cvat.apps.datumaro.task as DatumaroTask
5459  File "/home/django/cvat/apps/datumaro/task.py", line 18, in <module>
5460    from datumaro.components.project import Project
5461ImportError: No module named 'datumaro.components'
</details>
5462The command "docker exec -it cvat /bin/bash -c 'python3 manage.py test cvat/apps/engine utils/cli'" exited with 1.

**Comment by nmanovic** [comment]
@zhiltsov-max , look at DVC (https://github.com/iterative/dvc). Looks very similar to some ideas which we discussed.

**Comment by zhiltsov-max** [comment]
Added `datumaro_remote` "lightweight" export format which exports a project with annotations and remote image access info.

**Comment by nmanovic** [comment]
@zhiltsov-max ,

Could you please fix all problems with the build?

/bin/sh: 1: cannot open /home/django/cvat/apps/dataset_manager/dependencies/datumaro/requirements.txt: No such file

**Comment by nmanovic** [comment]
@zhiltsov-max, 

Also I see that datumaro is added as a submodule. Please avoid that. Please add datumaro into the root directory of cvat (near cvat-ui, coat-core, ...)

**Comment by zhiltsov-max** [comment]
@nmanovic, it should compile better now, I hope.

**Comment by nmanovic** [comment]
@zhiltsov-max , I disabled Prospector for cvat project.

**Comment by nmanovic** [comment]
@zhiltsov-max ,

```
$ docker exec -it cvat /bin/bash -c 'python3 manage.py test cvat/apps/engine utils/cli'
Creating test database for alias 'default'...
Getting flipped tasks...
Conversion started...
System check identified some issues:
WARNINGS:
?: (2_0.W001) Your URL pattern 'api/swagger.<slug:format>$' [name='schema-json'] has a route that contains '(?P<', begins with a '^', or ends with a '$'. This was likely an oversight when migrating to django.urls.path().
System check identified 1 issue (0 silenced).
..../usr/local/lib/python3.5/dist-packages/cacheops/redis.py:20: RuntimeWarning: The cacheops cache is unreachable! Error: Error 99 connecting to localhost:6379. Cannot assign requested address.
  warnings.warn("The cacheops cache is unreachable! Error: %s" % e, RuntimeWarning)
...............................................
The job exceeded the maximum time limit for jobs, and has been terminated.
```

Why `localhost:6379`?

**Comment by zhiltsov-max** [comment]
It's been there for a while, I've no clue. I suppose, it's related to `fakeredis` usage in tests, which doesn't rely on the actual redis. The task has just timed out.

**Pull request merged**
