### PR TITLE
Update documentation to point to OpenVino component documentation

### PR DESCRIPTION
**Pull request by benhoff**
Currently the documentation points to the application documentation rather than the component documentation. The app docs have usage instructions but not installation instructions.

### CODE REVIEW

**Comment by benhoff** [comment]
Also, do you actually need the CUDA repo as referenced in this [documentation](https://github.com/opencv/cvat/blob/develop/cvat/apps/documentation/installation.md#additional-components)? The Auto Annotation implementation is hardcoded to use the CPU, see [here](https://github.com/opencv/cvat/blob/73bab7bea6ab3d682e94a3c48ed89d6b55b8b48f/cvat/apps/auto_annotation/inference_engine.py#L26).

**Comment by nmanovic** [comment]
@benhoff , why do you think that the updated link is better? If I want to get information about Auto Annotation the link on openvino component doesn't provide a good info.

**Comment by benhoff** [comment]
@nmanovic I was changing the link because the overarching document is in the "Installation Guide". There's no link or information on how to install the Auto Annotation app from the overarching installation guide.

Maybe instead of changing the link, we should add links? So one link to see what the auto annotation app is, and one link for the instructions to install the application.

I was writing instructions for my team to install CVAT, and I wrote in several precursor steps to following the installation instructions, because the installation steps for CVAT is, in my opinion, confusing.

**Comment by benhoff** [comment]
1. Download OpenVino from [this link](https://software.intel.com/en-us/openvino-toolkit). Download the Ubuntu version.
2. Clone the CVAT repository. `$ git clone https://github.com/opencv/cvat.git`
3. Move the downloaded OpenVino .tgz installer to `cvat/components/openvino`.
4. Accept the end user license agreement in the `cvat/components/openvino/eula.cfg` file. See more [here](https://github.com/opencv/cvat/tree/develop/components/openvino) for more setup instructions and context.
4. If this is client facing, specify the ALLOWED_HOSTS environment variable in a new `docker-compose.override.yml` file in the root of the project. See [here](https://github.com/opencv/cvat/blob/develop/cvat/apps/documentation/installation.md#advanced-settings) for the format of the file.
5. *READ* the [CVAT installation instructions](https://github.com/opencv/cvat/blob/develop/cvat/apps/documentation/installation.md) for Ubuntu. NOTE: There's one important step before you follow all the instructions.
6. The important step is you're going to change the `$ docker-compose build` command/step. Instead you're going ot run: `docker-compose -f docker-compose.yml -f components/openvino/docker-compose.openvino.yml up -d --build`. You'll still run this command from the root of the repo.
7. Follow the steps of the CVAT installation, changing the step above.
8. You should be able to log in and see the web interface for CVAT now.
7. Clone the [Open Model Zoo](https://github.com/opencv/open_model_zoo). `$ git clone https://github.com/opencv/open_model_zoo.git`
8. Install the appropriate libraries. Currently that command would be `$ pip install -r open_model_zoo/tools/downloader/requirements.in`
9. Download the models using `downloader.py` file in `open_model_zoo/tools/downloader/`. The `--name` command can be used to specify specific models. The `--print_all` command can print all the available models. Specific models that are already integrated into Cvat can be found [here](https://github.com/opencv/cvat/tree/develop/utils/open_model_zoo).
10. From the web user interface in CVAT, upload the models using the model manager. You'll need to include the xml and bin file from the model downloader. You'll need to include the python and JSON files from scratch or by using the ones in the CVAT libary. See [here](https://github.com/opencv/cvat/tree/develop/cvat/apps/auto_annotation) for instructions for creating custom python and JSON files.
11. Run the model on your image.

**Comment by nmanovic** [comment]
@benhoff ,

I don't think that if we change the link we solve the mentioned problem.

My proposal is the following:
- Let's add one more link on OpenVINO component into the installation guide
- In auto annotation README.md we have the following sentence: `The application will be enabled automatically if OpenVINO™ component is installed.` I believe it should be enough.
- Let's improve OpenVINO component documentation using your instructions above. Probably you want to slightly rephrase some steps. For example, 

```markdown
- Let's assume you already cloned CVAT repository following instructions in the [installation guide](link here).
- Download Intel OpenVINO ...
```

What do you think?

**Comment by benhoff** [comment]
@nmanovic, I just sub-indented the installation instructions. Let me know if that doesn't work for you.

**Comment by nmanovic** [comment]
@benhoff , probably I'm wrong but I don't see that the patch changes something. First line of cvat/apps/auto_annotation/README.md document states that you have to install OpenVINO component (together with a link on the component). You added one more section with "installation" instructions.

The documentation can be definitely improved. I see a big value in your instructions how to build CVAT together with OpenVINO mentioned in comments to the PR but you don't try to contribute them.

**Comment by benhoff** [comment]
Hmm, let me take a look. I don't think I correctly understood which files were to be edited in your proposal below.

> * Let's add one more link on OpenVINO component into the installation guide
> * In auto annotation README.md we have the following sentence: `The application will be enabled automatically if OpenVINO™ component is installed.` I believe it should be enough.
> * Let's improve OpenVINO component documentation using your instructions above. Probably you want to slightly rephrase some steps. For example,
> 
> ```gfm
> - Let's assume you already cloned CVAT repository following instructions in the [installation guide](link here).
> - Download Intel OpenVINO ...
> ```

I see where I've missed the second bullet in the above list.

Maybe let me hack on the OpenVINO component docs a bit, resubmit, and then we'll have a good base to discuss what else needs doing.

**Comment by nmanovic** [comment]
@benhoff , thanks for the patch. I have slightly modified it. Hope it will work for you as well.

**Pull request merged**
