### PR TITLE
Bump Datumaro commit

### LINKED ISSUE #5048: Keypoint Numbering Messed up for COCO Keypoint export
### My actions before raising this issue
Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
Searched [past issues](https://github.com/opencv/cvat/issues?q=keypoint+is%3Aclosed)

When exporting keypoint annotations using the COCO keypoint annotation and then importing them back into CVAT, the keypoints are in the wrong order. I don't know if this is useful, but the annotation was done using the keypoint skeleton.

### Expected Behaviour
The annotations shouldn't change order when exported. It occurs on the export as I open them on another annotator to check. 
This does not occur when exporting in CVAT format.

### Current Behaviour
The key points are incorrect order. E.g Square is annotated as below.
```
1--2
|  |
4--3
```
When importing this back into CVAT the following may occur.
```
3--2
|  |
1--4
```

### Possible Solution
There doesn't seem to be a pattern in the changes I can see, but I assume this is happening in the conversion to COCO keypoint.

### Steps to Reproduce (for bugs)
1. Annotate images in CVAT using a keypoint skeleton 
2. Export annotations
3. Import annotations onto a copy of the dataset to visualise it.

### Context
I need this for a project, but this is also a bug in the performance.

### Your Environment
I am using the web browser version of CVAT on a linux ubunutu 20.04 OS, with Chrome as my browser.

### PR DESCRIPTION
**Pull request by SpecLad**
### Motivation and context

Fixes #5048.

### How has this been tested?

I reproduced #5048, then made sure it no longer reproduces with this change.

### Checklist

- [x] I submit my changes into the `develop` branch
- [x] I have added a description of my changes into [CHANGELOG](https://github.com/cvat-ai/cvat/blob/develop/CHANGELOG.md) file
- ~~[ ] I have updated the [documentation](
  https://github.com/cvat-ai/cvat/blob/develop/README.md#documentation) accordingly~~
- ~~[ ] I have added tests to cover my changes~~
- [x] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- ~~[ ] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/cvat-ai/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/cvat-ai/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/cvat-ai/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/cvat-ai/cvat/tree/develop/cvat-ui#versioning))~~

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/cvat-ai/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.

### CODE REVIEW

**Review by nmanovic — APPROVED** [review]
LGTM

**Comment by SpecLad** [comment]
I rebased it; should be good to go now.

**Pull request merged**
