### PR TITLE
added in label visualization to auto annotation runner

### PR DESCRIPTION
**Pull request by benhoff**
This should answer https://github.com/opencv/cvat/issues/914

### CODE REVIEW

**Comment by nmanovic** [comment]
@benhoff , I have found an issue in run_model.py. Could you please fix it and verify other cases?

```
python   ./utils/auto_annotation/run_model.py --py ../open_model_zoo/cvat/semantic-segmentaton-adas/interp.py --bin ../open_model_zoo/cvat/semantic-segmentation-adas/semantic-segmentation-adas-0001.bin --xml ../open_model_zoo/cvat/semantic-segmentation-adas/semantic-segmentation-adas-0001.xml --json ../open_model_zoo/cvat/semantic-segmentation-adas/mapping.json  --image-files ./data/34/data/0/0/0.jpg --show-images --show-labels
```

```
WARNING:root:Inference didn't have any errors.
Traceback (most recent call last):
  File "./utils/auto_annotation/run_model.py", line 196, in <module>
    main()
  File "./utils/auto_annotation/run_model.py", line 158, in main
    cv2.polylines(data, [points], 1, color)
cv2.error: OpenCV(4.1.2-openvino) /localdisk/jenkins/workspace/OpenCV/OpenVINO/build/opencv/modules/imgproc/src/drawing.cpp:2435: error: (-215:Assertion failed) p.checkVector(2, CV_32S) >= 0 in function 'polylines'
```

It seems that the reason is unnecessary pairwise second time.

**Comment by benhoff** [comment]
What model are you using? Polylines is a difficult function to feed correctly

**Comment by nmanovic** [comment]
> What model are you using? Polylines is a difficult function to feed correctly

@benhoff , semantic-segmentation-adas. You can find the full command line in my previous message.

**Comment by benhoff** [comment]
@nmanovic

**Comment by benhoff** [comment]
@nmanovic can you try now? I added a second call of the `pairwise` method accidentally. With that method removed, everything should work.

**Pull request merged**
