### PR TITLE
add yolov5 serverless function leveraging nvidia gpu

### LINKED ISSUE #4851: Unable to load the YOLOv5 on to the GPU
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

I have been trying to integrate the model yolov5m trained on Objects365 - https://github.com/ultralytics/yolov5/releases/download/v6.0/yolov5m_Objects365.pt  onto the GPU on CVAT

### Expected Behaviour
The custom YOLOv5 model to be accessed on the CVAT and be used for annotation using GPU. 

### Current Behaviour
The building fails and unable to load onto the GPU on CVAT. When deploying on CPU, it works. But not sure of the changes to be made to deploy using GPU
image

### Steps to Reproduce (for bugs)

- function-gpu.yaml - 
Changed the base image which was configured for CUDA version 10.2
image

- function-gpu.yaml 
Added the pip install requirements  and the torch and torchvision and download the model. 
image

The requirements are from here - [https://github.com/ultralytics/yolov5/blob/master/requirements.txt](url)

- function-gpu.yaml
The resources for GPU and changed the maxWorkers for triggers to 1 as read in one of the previous issues. 
image

- main.py
Access the downloaded weights file and load to the available cuda device (in my case, 1 GPU) and continue with inference. 
image

### Context
I am unable to resolve this issue no matter the changes I make in the main.py file or the function-gpu.yaml.

### Your Environment

- Docker version `docker version` : 20.10.17
- Operating System and version - Linux
- Code example or link to GitHub repo to access the model : [https://github.com/ultralytics/yolov5/releases/download/v6.0/yolov5m_Objects365.pt ](url)

- Other diagnostic information / logs:
    <details>
    <summary>

image

</summary>

 <summary>

image
</summary>
    </details>

Thank you for your kind help. Looking forward to any help/guidelines to solve the issue. 

Issue by @gd1925

### PR DESCRIPTION
**Pull request by tdhooghe**
Fixes #4851

This change enables leveraging an NVIDIA GPU when using a YOLOv5 serverless function.

### Motivation and context

This change speeds up auto labeling with a YOLOv5 model.

### How has this been tested?

Deploying the script using `deploy_gpu.sh` and checking if it uses the NVIDIA GPU with NVIDIA-SMI while auto-labeling.

### Checklist

- [x] I submit my changes into the `develop` branch
- [ ] I have added a description of my changes into [CHANGELOG](https://github.com/cvat-ai/cvat/blob/develop/CHANGELOG.md) file
- [ ] I have updated the [documentation](
  https://github.com/cvat-ai/cvat/blob/develop/README.md#documentation) accordingly
- [ ] I have added tests to cover my changes
- [x] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [ ] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/cvat-ai/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/cvat-ai/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/cvat-ai/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/cvat-ai/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/cvat-ai/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.

### CODE REVIEW

**Comment by azhavoro** [comment]
LGTM, worked for me

**Comment by azhavoro** [comment]
@tdhooghe Hi,
Thanks for the your contribution and could you add a line to the changelog about your change?

**Comment by bsekachev** [comment]
@tdhooghe 

Thank you for the contribution, I will add a line to CONTRIBUTING.md later.

**Comment by tdhooghe** [comment]
Hi Boris,

Apologies for my late response. I can still add a line in the changelog if
you want?

Kind regards,
Thomas

Op wo 12 okt. 2022 om 18:20 schreef Boris Sekachev ***@***.***

**Comment by bsekachev** [comment]
@tdhooghe 
Would be great, thank you.

**Pull request merged**
