### PR TITLE
[Datumaro] Added tf detection api tfrecord import and export

### LINKED ISSUE #866: Tfrecord Dump Error
If you dump annotation for `TFRecord Zip 1.0` then there will be a lot of problem with the dumped file.  (`/annotation/tfrecord.py`)

1) First problem is with `label_map.pbtxt`. The problem is `id = 0` is reserved for background. So, it needs to start from 1 NOT 0. This can easily be fixed.

2) Tfrecord contains encoded images so that training can be faster. But if you look at the current file, it does not encode images into tfrecord. If you use this tfrecord in TF Detection API, it will throw an error.

### PR DESCRIPTION
**Pull request by zhiltsov-max**
Related #869 
Closes #866 

Added support for TFrecord format from TF detection API.

### CODE REVIEW

**Comment by nmanovic** [comment]
I tried to export a dataset without success.

```
2019-12-04 12:31:23,105 DEBG 'rqworker_default_1' stderr output:
12:31:23 default: cvat.apps.dataset_manager.task.export_project('14', <SimpleLazyObject: <User: admin>>, 'tf_detection_api', 'localhost:8080') (task_dataset_export.14.tf_detection_api)

2019-12-04 12:32:04,292 INFO reaped unknown pid 196
2019-12-04 12:32:04,306 INFO reaped unknown pid 197
2019-12-04 12:32:04,316 DEBG received SIGCLD indicating a child quit
2019-12-04 12:32:04,349 DEBG 'rqworker_default_1' stderr output:
12:32:04 Moving job to FailedJobRegistry (work-horse terminated unexpectedly; waitpid returned 9)

2019-12-04 12:32:07,342 DEBG 'runserver' stderr output:
[Wed Dec 04 12:32:07.340035 2019] [wsgi:error] [pid 144:tid 140510903858944] [remote 172.20.0.1:37288] [2019-12-04 12:32:07,329] ERROR django.request: Internal Server Error: /api/v1/tasks/14/dataset
```

**Comment by nmanovic** [comment]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rq/worker.py", line 812, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python3.5/dist-packages/rq/job.py", line 588, in perform
    self._result = self._execute()
  File "/usr/local/lib/python3.5/dist-packages/rq/job.py", line 594, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/home/django/cvat/apps/dataset_manager/task.py", line 331, in export_project
    server_url=server_url)
  File "/home/django/cvat/apps/dataset_manager/task.py", line 221, in export
    save_dir=save_dir, save_images=save_images)
  File "/home/django/datumaro/datumaro/components/project.py", line 521, in export
    converter(dataset, save_dir)
  File "/home/django/datumaro/datumaro/components/converters/tfrecord.py", line 149, in __call__
    save_images=self.save_images,
  File "/home/django/datumaro/datumaro/components/converters/tfrecord.py", line 83, in _make_tf_example
    xmins.append(box.points[0] / width)
ZeroDivisionError: float division by zero
```

**Comment by nmanovic** [comment]
[task_test video-2019_12_06_11_19_59-datumaro_project.zip](https://github.com/opencv/cvat/files/3931914/task_test.video-2019_12_06_11_19_59-datumaro_project.zip)

**Comment by zhiltsov-max** [comment]
@nmanovic, please check if updates helped.

**Comment by nmanovic** [comment]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rq/worker.py", line 812, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python3.5/dist-packages/rq/job.py", line 588, in perform
    self._result = self._execute()
  File "/usr/local/lib/python3.5/dist-packages/rq/job.py", line 594, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/home/django/cvat/apps/dataset_manager/task.py", line 341, in export_project
    server_url=server_url)
  File "/home/django/cvat/apps/dataset_manager/task.py", line 221, in export
    save_dir=save_dir, save_images=save_images)
  File "/home/django/datumaro/datumaro/components/project.py", line 521, in export
    converter(dataset, save_dir)
  File "/home/django/datumaro/datumaro/components/converters/tfrecord.py", line 148, in __call__
    save_images=self.save_images,
  File "/home/django/datumaro/datumaro/components/converters/tfrecord.py", line 52, in _make_tf_example
    "Failed to export dataset item '%s': item has no image" % item.id)
Exception: Failed to export dataset item '100': item has no image
```

**Comment by nmanovic** [comment]
[task_road2-2019_12_09_11_15_03-datumaro_project.zip](https://github.com/opencv/cvat/files/3939450/task_road2-2019_12_09_11_15_03-datumaro_project.zip)

**Comment by zhiltsov-max** [comment]
@nmanovic, it should work now.

**Comment by nmanovic** [comment]
@zhiltsov-max ,

I will propose reproduce the issue on your side. I still have the problem with a video task without any annotations:

```
2019-12-11 14:50:08,189 DEBG 'rqworker_default_0' stderr output:
14:50:08 default: cvat.apps.dataset_manager.task.export_project('15', <User: admin>, 'tf_detection_api', 'localhost:8080') (task_dataset_export.15.tf_detection_api)

2019-12-11 14:50:27,426 DEBG 'rqworker_default_0' stderr output:
14:50:27 Moving job to FailedJobRegistry (work-horse terminated unexpectedly; waitpid returned 9)

2019-12-11 14:50:27,546 DEBG 'rqworker_default_0' stderr output:
14:50:27 Cleaning registries for queue: default

2019-12-11 14:50:28,155 DEBG 'runserver' stderr output:
[Wed Dec 11 14:50:28.153642 2019] [wsgi:error] [pid 180:tid 140068525729536] [remote 172.20.0.1:54968] [2019-12-11 14:50:28,152] ERROR django.request: Internal Server Error: /api/v1/tasks/15/dataset
```

**Comment by nmanovic** [comment]
[task_test video-2019_12_12_08_13_12-datumaro_project.zip](https://github.com/opencv/cvat/files/3954568/task_test.video-2019_12_12_08_13_12-datumaro_project.zip)

**Pull request merged**
