### PR TITLE
Fix most discrepancies between the different ways of generating the API schema

### PR DESCRIPTION
**Pull request by SpecLad**
### Motivation and context

Currently, if you try to generate the API schema with the VS Code launch configuration, it'll remove the `minimum` and `maximum` attributes from the definition of some of the integer fields. This is because those attributes come from the configured database engine in use. The "canonical" version of the schema is generated from the Docker image, which uses the production configuration, and thus PostgreSQL; while using the VS Code launch configuration will default to the development configuration, and thus SQLite.

Fix it by aligning the configurations. Since ultimately, the schema is for the production version of the server, override the configuration to production for the VS Code launch configuration.

Note that there's one more discrepancy that remains; that of the API version number. I haven't figured out the best way to fix that yet.

### How has this been tested?

By pressing F5 🙂 

### Checklist

- [x] I submit my changes into the `develop` branch
- ~~[ ] I have added a description of my changes into the [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file~~
- ~~[ ] I have updated the documentation accordingly~~
- ~~[ ] I have added tests to cover my changes~~
- ~~[ ] I have linked related issues (see [GitHub docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))~~
- ~~[ ] I have increased versions of npm packages if it is necessary
  ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
  [cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning),
  [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and
  [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))~~

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.

### CODE REVIEW

**Comment by SpecLad** [comment]
CC @Marishka17  @zhiltsov-max

**Comment by zhiltsov-max** [comment]
Probably, this should not depend on the database used, but I agree with this as a quick fix. However, there seem to be a problem with dependencies in the development environment because Apache is not installed.

**Comment by zhiltsov-max** [comment]
No, it fails to compile a package because Apache is required.

**Review by nmanovic — DISMISSED** [review]

**Comment by SpecLad** [comment]
> No, it fails to compile a package because Apache is required. I understand that it needs to be installed, but I suggest to add such notes to the development environment configuration steps then.

Fair point. I did it.

**Pull request merged**
