### PR TITLE
Batch of fixes

### LINKED ISSUE #1351: Duplicated settings for default marking type.
In annotation.html there is

`        <select id="shapeTypeSelector" class="regular h2">
            <option value="box" class="regular" selected> Box </option>
            <option value="box_by_4_points" class="regular" selected> Box by 4 points </option>`

Where both of these items are marked as selected.  However, in shapeCreator.js line 235 does the following:

` this._typeSelector.val('box');`

This creates some redundancy.

### LINKED ISSUE #1356: Layout doesn't fit to HDPI displays
On small displays with high resolution (tested on 15'' FHD display, W10, Firefox 76 & Chrome 80) layout does not completely fit to the browser window (able to scroll page)  

изображение

изображение

### PR DESCRIPTION
**Pull request by bsekachev**
### Motivation and context
PR increases quality of the tool and resolves some critical issues

### How has this been tested?
Manual testing

### Checklist
- [x] I have raised an issue to propose this change ([required](https://github.com/opencv/cvat/issues))

~~- [ ] My issue has received approval from the maintainers~~

- [x] I've read the [CONTRIBUTION](https://github.com/opencv/cvat/blob/develop/CONTRIBUTING.md) guide
- [x] I have added description of my changes into [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file

~~- [ ] I have updated the [documentation](
  https://github.com/opencv/cvat/blob/develop/README.md#documentation)~~

~~- [ ] I have added tests to cover my changes~~

- [x] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [x] I have updated the license header for each file (see an example below)

Resovled #1368
Resolved #1356
Resolved #1351
Related #1343

@nmanovic 
Making a PR is getting difficult

### CODE REVIEW

**Comment by nmanovic** [comment]
@bsekachev , 

> Making a PR is getting difficult

Let's discuss how to improve the template on our team meeting. But now it has all required information which is important to track changes in the huge project.

**Comment by nmanovic** [comment]
@ActiveChooN , please review ASAP. It contains some critical fixes for the community and our internal CVAT instance.

**Comment by bsekachev** [comment]
@nmanovic 
One more review is required. Why?

**Comment by ActiveChooN** [comment]
> 
> 
> @nmanovic
> One more review is required. Why?

I guess because we added codeowners for different folders in projects

**Pull request merged**
