### PR TITLE
Single-point interpolation

### PR DESCRIPTION
**Pull request by bsekachev**
Feature: Support of interpolation for a single point.

### CODE REVIEW

**Comment by alex9311** [comment]
does "single-point" mean keypoints or single point polygons?

**Comment by foreverYoungGitHub** [comment]
How could I use this function? I build the library from develop branch, and it seems that it could not work. As long as I pick 'points', it shows only 'annotation' mode allowed. When I pick the interpolation mode, it shows only boxes and single point allowed.

**Comment by alex9311** [comment]
> How could I use this function? I build the library from develop branch, and it seems that it could not work. As long as I pick 'points', it shows only 'annotation' mode allowed. When I pick the interpolation mode, it shows only boxes and single point allowed.

You probably aren't setting the "Poly Shape Size" to 1 in the bottom right part of the screen

poly-shape-size

**Comment by foreverYoungGitHub** [comment]
Yes, you are correct.

Is there any plan to add the multiple points interpolation in the code recently? The interpolation way should be same and fast. 

Also another small issue I found is that when I merge the points in different frame to a track, all the frame is keyframe(I can expect that), however when I set one of the annotation as un-keyframe, the annotation directly disappear.

I'm not familiar with the js, please let me know if I can help something to accelerate the function.

Best,

**Comment by nmanovic** [comment]
@foreverYoungGitHub , it is possible to implement and probably it will be added in the future. Right now we are busy with other features. If you can help you are welcome. We are ready to support all people who want to contribute.

**Pull request merged**
