### PR TITLE
[WIP] Multiselect

### PR DESCRIPTION
**Pull request by docwhat**
- initial commit
- Added support for multi-select in all the layers, trigger multiselect with shift+click in canvas + object list, made contextmenu show all active items
- click-drag box multi-select behavior
- tied up loose ends with multi-select
- achieved all desired pointer behavior
- made object keyboard shortcuts work on all selected objects
- mega merge
- made label change hotkeys work on multiple selected objects
- initial label grouping
- group objects by label, reusable label-item component
- achieved desired styling
- fixed merge issues with removing objects from object list menu
- fixes and todo cleanup
- prevent clicking on label shortcut dropdown toggling the object group
- BN-2881 - tie collapseAll button to label groups
- fixed consecutive selection-box drawing
- docker-compose sans infrastructure for GCP deployment
- updating docker-compose
- update to use gcr images
- updated readme
- updated readme
- more readme stuff
- added build to readme
- updated image repos
- added more envars to readme
- readme update
- made ctrl prevent selecting/editing other shapes
- brought back memoization comparer to prevent unneeded object-item redraws that were impacting performance
- virtualized the nested object list
- virtualized the contextmenu
- delete multiple objects at once as a single action
- fixed all label contextmenu option
- use cvat_ui:0.0.1
- Optimized removing shapes from the canvas during a frame change
- optimized removing all objects on frame change
- display version number
- fixed clearing labels in the optimized reset canvas path

This adds the ability to select multiple bounding boxes at once.  This allows
managing labels for many boxes at one time.

I'm posting this now just so that people can look at this. This code is very
and have evolved in private but I'd like to see it in CVAT proper eventually.

Related: #5473

### Motivation and context

We work with images that are over 1GiB and that have 100s of bounding boxes.

### How has this been tested?

In (our) production.

### Checklist

- [ ] I submit my changes into the `develop` branch
- [ ] I have added a description of my changes into the [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] I have linked related issues (see [GitHub docs](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [ ] I have increased versions of npm packages if it is necessary
  ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
  [cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning),
  [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and
  [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))

### License

- [ ] I submit _my code changes_ under the same [MIT License](https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.

### CODE REVIEW

**Comment by docwhat** [comment]
@nmanovic Here is our code.  It's not pretty, and I don't know enough about CVAT to offer pre-emptive help. Feel free to ask questions, though.  I'll see if I can get you answers.

**Comment by nmanovic** [comment]
@docwhat , thank you for the contribution. It looks like current patch has a lot of merge conflicts. It will require significant efforts from our team to adapt these changes and cover them by tests.  As discussed in the meeting, we are ready to take the task and probably others if you need that. Happy to help our customers.

**Comment by GeorgePearse** [comment]
Would love this feature (click and drag to multi-select boxes and delete or relabel)

**Comment by bsekachev** [comment]
I will close the PR for now. If you are ready to carry on you work, you are always welcome

**Comment by docwhat** [comment]
Alas; the company I was doing this work for is gone.  Sorry.  Maybe someone else will be interested in pulling apart the patch.

**Comment by kurtjcu** [comment]
This would be great. :)

**Comment by docwhat** [comment]
Yeah, I'm glad I managed to get this out before the company went under.

**Pull request closed without merging**
