### PR TITLE
Fixed default undefined, fixed double change

### PR DESCRIPTION
**Pull request by bsekachev**
Switch source when change zOrder, occluded, outside, keyframe since they are part of position
Fixed double undo/redo actions on every change
Fixed undefined source on client

### Motivation and context
Some fixes for recent PR #1192 

### How has this been tested?
Manual testing

### Checklist

- [x] I submit my changes into the `develop` branch
- [ ] I have added description of my changes into [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
- [ ] I have updated the [documentation](
  https://github.com/opencv/cvat/blob/develop/README.md#documentation) accordingly
- [ ] I have added tests to cover my changes
- [ ] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [x] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [x] I have updated the license header for each file (see an example below)

```python
# Copyright (C) 2020 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

### CODE REVIEW

**Comment by nmanovic** [comment]
@Priya4607 , could you please test and review the patch?

**Comment by Priya4607** [comment]
> @Priya4607 , could you please test and review the patch?

Sure, I'll test it this weekend.

**Comment by Priya4607** [comment]
@bsekachev  
Hi, one quick question, how does switching source in case of occluded, keyframe, outside work. As in when I switch to occlusion for an auto annotated box will it change to manual?

**Comment by bsekachev** [comment]
> Hi, one quick question, how does switching source in case of occluded, keyframe, outside work. As in when I switch to occlusion for an auto annotated box will it change to manual?

Yes

**Comment by Priya4607** [comment]
> > Hi, one quick question, how does switching source in case of occluded, keyframe, outside work. As in when I switch to occlusion for an auto annotated box will it change to manual?
> 
> Yes

But when I switch occluded for auto annotated box, I notice that the value does not change to manual. Unless I move the box.

**Comment by bsekachev** [comment]
@Priya4607 

Hmm, yes. Actually I checked it only for tracks. Now it is fixed.

**Pull request merged**
