### PR TITLE
Updated rego rules, job assignee can resolve an issue

### LINKED ISSUE #4778: Annotators with "user" accounts have no permissions to resolve issues after reviews
Having "user" account, I am not able to resolve an issue, created during review by admin. 
I think user shall have the permission to resolve issues which shows the admin, that issue has been resolved. 

Please let me know if there is a solution for this behavior or this is actually a bug.This was not happening in the last versions. 

image
image

### PR DESCRIPTION
**Pull request by bsekachev**
### Motivation and context
Resolved #4778

### Checklist

- [x] I submit my changes into the `develop` branch
- [x] I have added a description of my changes into [CHANGELOG](https://github.com/cvat-ai/cvat/blob/develop/CHANGELOG.md) file
- [ ] I have updated the [documentation](
  https://github.com/cvat-ai/cvat/blob/develop/README.md#documentation) accordingly
- [ ] I have added tests to cover my changes
- [x] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [ ] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/cvat-ai/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/cvat-ai/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/cvat-ai/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/cvat-ai/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/cvat-ai/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.

### CODE REVIEW

**Comment by bsekachev** [comment]
@nmanovic 
Can you check this patch?

**Review by nmanovic — APPROVED** [review]
LGTM

**Pull request merged**
