### PR TITLE
[Snyk] Upgrade tus-js-client from 2.3.2 to 3.0.1

### PR DESCRIPTION
**Pull request by azhavoro**
<p>This PR was automatically created by Snyk using the credentials of a real user.</p><br /><h3>Snyk has created this PR to upgrade tus-js-client from 2.3.2 to 3.0.1.</h3>

merge advice
:information_source: Keep your dependencies up-to-date. This makes it easier to fix existing vulnerabilities and to more quickly identify and fix newly disclosed vulnerabilities when they affect your project.
<hr/>

*Warning:* This is a major version upgrade, and may be a breaking change.
- The recommended version is **3 versions** ahead of your current version.
- The recommended version was released **a month ago**, on 2022-09-09.

<details>
<summary><b>Release notes</b></summary>
<br/>
  <details>
    <summary>Package name: <b>tus-js-client</b></summary>
    <ul>
      <li>
        <b>3.0.1</b> - <a href="https://snyk.io/redirect/github/tus/tus-js-client/releases/tag/v3.0.1">2022-09-09</a></br><h2>What's Changed</h2>
<ul>
<li>Fix <code>Cannot call a namespace</code> error by <a class="user-mention notranslate" data-hovercard-type="user" data-hovercard-url="/users/aduh95/hovercard" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="https://snyk.io/redirect/github/aduh95">@ aduh95</a> in <a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="1364597013" data-permission-text="Title is private" data-url="https://github.com/tus/tus-js-client/issues/458" data-hovercard-type="pull_request" data-hovercard-url="/tus/tus-js-client/pull/458/hovercard" href="https://snyk.io/redirect/github/tus/tus-js-client/pull/458">#458</a></li>
<li>Require to use extensions in import specifiers by <a class="user-mention notranslate" data-hovercard-type="user" data-hovercard-url="/users/aduh95/hovercard" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="https://snyk.io/redirect/github/aduh95">@ aduh95</a> in <a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="1365923781" data-permission-text="Title is private" data-url="https://github.com/tus/tus-js-client/issues/459" data-hovercard-type="pull_request" data-hovercard-url="/tus/tus-js-client/pull/459/hovercard" href="https://snyk.io/redirect/github/tus/tus-js-client/pull/459">#459</a></li>
<li>Update many dependencies</li>
</ul>
<h2>New Contributors</h2>
<ul>
<li><a class="user-mention notranslate" data-hovercard-type="user" data-hovercard-url="/users/aduh95/hovercard" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="https://snyk.io/redirect/github/aduh95">@ aduh95</a> made their first contribution in <a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="1364597013" data-permission-text="Title is private" data-url="https://github.com/tus/tus-js-client/issues/458" data-hovercard-type="pull_request" data-hovercard-url="/tus/tus-js-client/pull/458/hovercard" href="https://snyk.io/redirect/github/tus/tus-js-client/pull/458">#458</a></li>
</ul>
<p><strong>Full Changelog</strong>: <a class="commit-link" href="https://snyk.io/redirect/github/tus/tus-js-client/compare/v3.0.0...v3.0.1"><tt>v3.0.0...v3.0.1</tt></a></p>
      </li>
      <li>
        <b>3.0.0</b> - <a href="https://snyk.io/redirect/github/tus/tus-js-client/releases/tag/v3.0.0">2022-08-03</a></br><p>This major release contains many features and bug fixes but also breaking changes! Please see the <a href="https://tus.io/blog/2022/08/03/tus-js-client-300.html" rel="nofollow">blog post</a> for details.</p>
      </li>
      <li>
        <b>3.0.0-0</b> - <a href="https://snyk.io/redirect/github/tus/tus-js-client/releases/tag/v3.0.0-0">2022-06-07</a></br><p>3.0.0-0</p>
      </li>
      <li>
        <b>2.3.2</b> - <a href="https://snyk.io/redirect/github/tus/tus-js-client/releases/tag/v2.3.2">2022-05-31</a></br><h2>What's Changed</h2>
<ul>
<li>Bump many dependencies</li>
<li>Make DetailedError extends Error in types by <a class="user-mention notranslate" data-hovercard-type="user" data-hovercard-url="/users/vkrol/hovercard" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="https://snyk.io/redirect/github/vkrol">@ vkrol</a> in <a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="1175876831" data-permission-text="Title is private" data-url="https://github.com/tus/tus-js-client/issues/329" data-hovercard-type="pull_request" data-hovercard-url="/tus/tus-js-client/pull/329/hovercard" href="https://snyk.io/redirect/github/tus/tus-js-client/pull/329">#329</a></li>
<li>Export DetailedError from package by <a class="user-mention notranslate" data-hovercard-type="user" data-hovercard-url="/users/vkrol/hovercard" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="https://snyk.io/redirect/github/vkrol">@ vkrol</a> in <a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="1175871855" data-permission-text="Title is private" data-url="https://github.com/tus/tus-js-client/issues/327" data-hovercard-type="pull_request" data-hovercard-url="/tus/tus-js-client/pull/327/hovercard" href="https://snyk.io/redirect/github/tus/tus-js-client/pull/327">#327</a></li>
</ul>
<h2>New Contributors</h2>
<ul>
<li><a class="user-mention notranslate" data-hovercard-type="user" data-hovercard-url="/users/vkrol/hovercard" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="https://snyk.io/redirect/github/vkrol">@ vkrol</a> made their first contribution in <a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="1175874666" data-permission-text="Title is private" data-url="https://github.com/tus/tus-js-client/issues/328" data-hovercard-type="pull_request" data-hovercard-url="/tus/tus-js-client/pull/328/hovercard" href="https://snyk.io/redirect/github/tus/tus-js-client/pull/328">#328</a></li>
</ul>
<p><strong>Full Changelog</strong>: <a class="commit-link" href="https://snyk.io/redirect/github/tus/tus-js-client/compare/v2.3.1...v2.3.2"><tt>v2.3.1...v2.3.2</tt></a></p>
      </li>
    </ul>
    from <a href="https://snyk.io/redirect/github/tus/tus-js-client/releases">tus-js-client GitHub release notes</a>
  </details>
</details>

<details>
  <summary><b>Commit messages</b></summary>
  </br>
  <details>
    <summary>Package name: <b>tus-js-client</b></summary>
    <ul>
      <li><a href="https://snyk.io/redirect/github/tus/tus-js-client/commit/20546a24779354e0c5e0b57e98c53c99652654cc">20546a2</a> 3.0.1</li>
      <li><a href="https://snyk.io/redirect/github/tus/tus-js-client/commit/aed3e8420e3105610bebdb6f6de3322495079484">aed3e84</a> require to use extensions in import specifiers (#459)</li>
      <li><a href="https://snyk.io/redirect/github/tus/tus-js-client/commit/f07ed8eb2b2d1709722a66d633434ac52f121e95">f07ed8e</a> Bump @ babel/preset-env from 7.18.10 to 7.19.0 (#461)</li>
      <li><a href="https://snyk.io/redirect/github/tus/tus-js-client/commit/03631a9b10a91547bfc79b416b2f9dc2c459fd48">03631a9</a> Bump jasmine from 4.3.0 to 4.4.0 (#462)</li>
      <li><a href="https://snyk.io/redirect/github/tus/tus-js-client/commit/d2fa4dd95601178b707e974d7eb821b8bdb7657e">d2fa4dd</a> Bump eslint-plugin-react from 7.30.1 to 7.31.8 (#460)</li>
      <li><a href="https://snyk.io/redirect/github/tus/tus-js-client/commit/22a723453699647bdbc59561b0cae54b019b71d9">22a7234</a> Fix &#x60;Cannot call a namespace&#x60; error (#458)</li>
      <li><a href="https://snyk.io/redirect/github/tus/tus-js-client/commit/754eca6408303fc66e6401668050d8b37c22c3c9">754eca6</a> Bump puppeteer from 16.1.0 to 17.1.3 (#464)</li>
      <li><a href="https://snyk.io/redirect/github/tus/tus-js-client/commit/fbf393af70a80f1880cb4bf3fd83c7b5a9ddd7c8">fbf393a</a> Bump eslint-plugin-react from 7.30.1 to 7.31.7 (#456)</li>
      <li><a href="https://snyk.io/redirect/github/tus/tus-js-client/commit/5fc33e3af952fd61e3af4703882d8d1c008fa6e1">5fc33e3</a> Bump uglify-js from 3.16.3 to 3.17.0 (#444)</li>
      <li><a href="https://snyk.io/redirect/github/tus/tus-js-client/commit/dd2c16a2513e94575065720ab67509df34219cbc">dd2c16a</a> Bump tsd from 0.22.0 to 0.23.0 (#449)</li>
      <li><a href="https://snyk.io/redirect/github/tus/tus-js-client/commit/a09930913936815722461c20ca1ba1370fb3b5f5">a099309</a> Bump @ babel/core from 7.18.10 to 7.19.0 (#457)</li>
      <li><a href="https://snyk.io/redirect/github/tus/tus-js-client/commit/14c3634e0ccd45973e90a3e460ca5e749f630107">14c3634</a> Phrase docs for chunkSize more strongly /cc @ Murderlon</li>
      <li><a href="https://snyk.io/redirect/github/tus/tus-js-client/commit/6be06f623332b909c2d557757081ec4a9989b713">6be06f6</a> Improve documentation for storeFingerprintsForResuming</li>
      <li><a href="https://snyk.io/redirect/github/tus/tus-js-client/commit/b03fac5f78b41c04ae46276ddc4f295589c3be33">b03fac5</a> Remove non-existing callback argument for terminate</li>
      <li><a href="https://snyk.io/redirect/github/tus/tus-js-client/commit/54f740680645c62e8cfd5556cc2f78ab0fac7c3e">54f7406</a> Bump puppeteer from 15.5.0 to 16.1.0 (#441)</li>
      <li><a href="https://snyk.io/redirect/github/tus/tus-js-client/commit/52d9693512586e7a3eb358cb917697976a2fc147">52d9693</a> Add information about bundle sizes</li>
      <li><a href="https://snyk.io/redirect/github/tus/tus-js-client/commit/99506d605b68994765fe2612c90092711acf435e">99506d6</a> Fix link to v3 blog post</li>
      <li><a href="https://snyk.io/redirect/github/tus/tus-js-client/commit/2b567c4d5f2bd36e2a00fbc41bfa96071003b1de">2b567c4</a> 3.0.0</li>
      <li><a href="https://snyk.io/redirect/github/tus/tus-js-client/commit/463d61dad02177bd42c8264602e849011e3ed564">463d61d</a> Update README</li>
      <li><a href="https://snyk.io/redirect/github/tus/tus-js-client/commit/bafe931887f4e46dfd2bb31d653761cc1cb4b912">bafe931</a> Rename HttpStack to DefaultHttpStack (#241)</li>
      <li><a href="https://snyk.io/redirect/github/tus/tus-js-client/commit/169b099eae1cab3bf9b98e8dcdcf7ffca14c5e6b">169b099</a> Add parallelUploadBoundaries option (#299)</li>
      <li><a href="https://snyk.io/redirect/github/tus/tus-js-client/commit/cc217787e03630bfb94706812a5b51e7affcc24b">cc21778</a> Improve documentation for chunkSize</li>
      <li><a href="https://snyk.io/redirect/github/tus/tus-js-client/commit/72c91c4ed090d81f6474159e3156d3a87fbab7cf">72c91c4</a> Support parallelUploads with fs.ReadStream</li>
      <li><a href="https://snyk.io/redirect/github/tus/tus-js-client/commit/f36640aecd2eb7e3b45bd77bb8bb86ecaf326a88">f36640a</a> fixup! Do not close source for abort, but for onSuccess</li>
    </ul>

   <a href="https://snyk.io/redirect/github/tus/tus-js-client/compare/50bebec8ad5a40fd3f14d0b48ffb7bd6c8a5a214...20546a24779354e0c5e0b57e98c53c99652654cc">Compare</a>
  </details>
</details>
<hr/>

**Note:** *You are seeing this because you or someone else with access to this repository has authorized Snyk to open upgrade PRs.*

For more information:  

🧐 [View latest project report](https://app.snyk.io/org/cvat/project/31502ad1-28fd-42cc-a9f7-f2efd57910e3?utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr)

🛠 [Adjust upgrade PR settings](https://app.snyk.io/org/cvat/project/31502ad1-28fd-42cc-a9f7-f2efd57910e3/settings/integration?utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr)

🔕 [Ignore this dependency or unsubscribe from future upgrade PRs](https://app.snyk.io/org/cvat/project/31502ad1-28fd-42cc-a9f7-f2efd57910e3/settings/integration?pkg&#x3D;tus-js-client&amp;utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr#auto-dep-upgrades)

### CODE REVIEW

**Comment by bsekachev** [comment]
@klakhov  Do you think we can update ``tus``?

**Comment by klakhov** [comment]
@bsekachev let me check if everything works correctly after update

**Comment by nmanovic** [comment]
@klakhov , should we update the lock file?

**Comment by kirill-sizov** [comment]
There is no any vulnerabilities, so I guess we can close this PR.
The reason why Snyk sent this PR is "Upgrade out-of-date dependency" option that was enabled for our repository.
I think that updating dependencies without any vulnerabilities is unnecessary so I disabled this option and expect that we won't receive such PRs in future.

**Comment by bsekachev** [comment]
@klakhov 

Looks like timeout issue. It is not related with this patch. Just bad connection with GitHub..

**Review by klakhov — APPROVED** [review]
Then I think we can merge this, tested locally, didn't meet any issues

**Pull request merged**
