### PR TITLE
Allow to configure SSL options: sslmode, sslcert, sslkey sslrootcert

### LINKED ISSUE #6323: Cannot connect to external PostgreSQL which has SSL enabled
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

Right now it is not possible to configure cvat to connect to external PostgreSQL server which requires SSL. You can only set the following variables to configure connection to postgres
```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'HOST': os.getenv('CVAT_POSTGRES_HOST', 'cvat_db'),
        'NAME': os.getenv('CVAT_POSTGRES_DBNAME', 'cvat'),
        'USER': os.getenv('CVAT_POSTGRES_USER', 'root'),
        'PASSWORD': os.getenv('CVAT_POSTGRES_PASSWORD', ''),
        'PORT': os.getenv('CVAT_POSTGRES_PORT', 5432),
    }
}
```

### Possible Solution

Add another variable CVAT_POSTGRES_SSL_MODE to the configuration
```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'HOST': os.getenv('CVAT_POSTGRES_HOST', 'cvat_db'),
        'NAME': os.getenv('CVAT_POSTGRES_DBNAME', 'cvat'),
        'USER': os.getenv('CVAT_POSTGRES_USER', 'root'),
        'PASSWORD': os.getenv('CVAT_POSTGRES_PASSWORD', ''),
        'PORT': os.getenv('CVAT_POSTGRES_PORT', 5432),
        'OPTIONS': {'sslmode': os.getenv('CVAT_POSTGRES_SSL_MODE', 'disable')},
    }
}
```

### Context

I'm trying to connect to an external PostgreSQL database which requires SSL.

### PR DESCRIPTION
**Pull request by rychuhardy**
Allow to configure SSL options: sslmode, sslcert, sslkey sslrootcert in the DATABASES setting in base.py. Added corresponding helm variables and updated Deployments to set these variables as environment variables.

### Motivation and context

Fixes #6323 

### How has this been tested?

Tested manually:

Given the following values.override.yml file:
```
postgresql:
  enabled: false
  external: 
    host: test.com
    port: 5432
    ssl_mode: require
    ssl_cert: /opt/certificate
    ssl_key: /opt/key
    ssl_root_cert: /opt/root_certificate
```

I've ran this command and reviewed output:
```
helm template --namespace cvat-helm cvat ./helm-chart -f ./helm-chart/values.yaml -f ./helm-chart/values.override.yml > template.yml
```

### Checklist

- [x] I submit my changes into the `develop` branch
- [ ] I have added a description of my changes into the [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [x] I have linked related issues (see [GitHub docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [ ] I have increased versions of npm packages if it is necessary
  ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
  [cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning),
  [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and
  [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.

### CODE REVIEW

**Comment by azhavoro** [comment]
@rychuhardy Thanks for the contribution! We will try to look and test PR as soon as we can

**Comment by rychuhardy** [comment]
Just checking if there's anything to do from side or if you are just still going to review it?

**Comment by nmanovic** [comment]
@rychuhardy , thank you for the contribution. Will you mind resolving conflicts to merge the PR?

**Comment by rychuhardy** [comment]
@nmanovic Sure, I have updated the PR.

**Comment by nmanovic** [comment]
@rychuhardy , could you please add an information about the change into CHANGELOG? 

```
<!--
  Developers: this project uses scriv (<https://scriv.readthedocs.io/en/stable/index.html>)
  to maintain the changelog. To add an entry, create a fragment:

    $ scriv create --edit

  Fragments will be merged into this file whenever a release is made.
-->

```

**Comment by nmanovic** [comment]
@SpecLad , could you please look?

**Comment by SpecLad** [comment]
I think it's already possible to apply these settings by using the [`PG*` environment variables](https://www.postgresql.org/docs/current/libpq-envars.html). It's possible to set custom environment variables in Helm deployments using the `*.additionalEnv` values. Have you tried doing this?

**Comment by rychuhardy** [comment]
> I think it's already possible to apply these settings by using the [`PG*` environment variables](https://www.postgresql.org/docs/current/libpq-envars.html). It's possible to set custom environment variables in Helm deployments using the `*.additionalEnv` values. Have you tried doing this?

I've just tried them. It seems to be working, although I have to add these flags to each component.
Thanks

**Comment by SpecLad** [comment]
I've now added a `cvat.backend.additionalEnv` parameter to the Helm chart, which lets you add an environment variable to every backend pod. Given that, I think adding PostgreSQL SSL-specific parameters would definitely be redundant. So I'm going to close this PR.

**Pull request closed without merging**
