### PR TITLE
Fix coverage merging

### PR DESCRIPTION
**Pull request by zhiltsov-max**
### Motivation and context

Merges coverage results correctly

### Checklist

- [x] I submit my changes into the `develop` branch
- [ ] I have added description of my changes into [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
- [ ] I have updated the [documentation](
  https://github.com/opencv/cvat/blob/develop/README.md#documentation) accordingly
- [ ] I have added tests to cover my changes
- [ ] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [x] I have updated the license header for each file (see an example below)

```python
# Copyright (C) 2020 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

### CODE REVIEW

**Comment by zhiltsov-max** [comment]
@nmanovic, how about putting a coverage badge in the PR footer?

**Comment by nmanovic** [comment]
@zhiltsov-max , a great idea. Will you send a PR to make the change?

**Comment by zhiltsov-max** [comment]
@nmanovic, can this be done by a PR?

**Comment by zhiltsov-max** [comment]
It seems that it can be done like this: https://stackoverflow.com/questions/35260896/coveralls-not-sending-pull-request-status

**Pull request merged**
