### PR TITLE
Add in ability to run Auto Annotation model using model name and task id

### PR DESCRIPTION
**Pull request by benhoff**
This needs to be tested extensively and I'm not a spot to do it currently.

This should resolve https://github.com/opencv/cvat/issues/913

@nmanovic, do you want me to merge these two pull requests? I didn't think about it until now.

### CODE REVIEW

**Comment by nmanovic** [comment]
> This needs to be tested extensively and I'm not a spot to do it currently.
> 
> This should resolve #913
> 
> This is dependent on #931.
> 
> @nmanovic, do you want me to merge these two pull requests? I didn't think about it until now.

@benhoff ,

If your PRs are ready please remove WIP and I will start the review.

**Comment by nmanovic** [comment]
@benhoff , thanks for the contribution. I really don't think that we have to merge the PR. Let me explain reasons behind that:
1. We are going to change layout of the task directory soon. Thus the script will not work after that. It tries to rely on something which it should not (how CVAT keeps files internally).
1. I don't think any problems for the user to run the original script inside the docker container. Why do we need an extra helper here? I don't see any reason for that.

**Comment by benhoff** [comment]
@nmanovic 

It's difficult to debug a script with a user. See here: https://github.com/opencv/cvat/issues/896

Right now, because the "test case" for a submit of files into CVAT is an all black image, so it's easy to submit non-working code up into the server.

Once the code has been uploaded to the server, it's hard to get a debug script out of the server with the low level information of a traceback that `run_model.py` provides.

In the case of https://github.com/opencv/cvat/issues/896, I knew there was an issue with the code they had loaded in the server, but I couldn't figure out how to get the users to provide a traceback back to me. 

CVAT logs are too large to submit up to Github.

One user tried to run the `run_model.py` code outside of the server, but because they didn't have OpenVINO correctly installed (they forgot to activate the script to add it to their path). Debugging over email is difficult, and I didn't know what they environment was like, except I did know that they had it installed successfully in docker.

Hopefully that explains the reasoning for your second point. Is there a good way to address your first point?

**Comment by nmanovic** [comment]
@benhoff , if you think that it is useful I will be glad to merge the PR. But https://github.com/opencv/cvat/pull/787 is going to break the new feature. I hope you will help us to fix that in the future. Thanks again for all your time which you spend on the project!

**Pull request merged**
