### PR TITLE
Added in new interp files for pixel link v0004

### PR DESCRIPTION
**Pull request by benhoff**
The open model zoo changed the keys between version 0002 and 0004.

### CODE REVIEW

**Comment by benhoff** [comment]
@dzimmerman-nci , FYSA. I fixed the dictionary keys for pixel link so you didn't have to mess with it.

**Comment by benhoff** [comment]
For the Codacy issues that are flagged on this commit, there's still an issue with the way things are implemented using Python's eval, you can't do multilevel method names. 

See here: #652 -and- this pull request: https://github.com/opencv/cvat/pull/794

**Comment by nmanovic** [comment]
> For the Codacy issues that are flagged on this commit, there's still an issue with the way things are implemented using Python's eval, you can't do multilevel method names.
> 
> See here: #652 and this pull request: #794

@benhoff , thanks for the PR. We have an internal discussion about another PR and decide to explicitly disable all warnings like that to make codacy green. Could you please just add a couple of comments to hide these warnings (e.g. `# pylint: disable=no-self-use`?

**Comment by benhoff** [comment]
@nmanovic updated!

**Comment by nmanovic** [comment]
@benhoff , I have merged. Thank you! Could you please update CHANGELOG.md and add licensing terms into your files? Something like:

```
# SPDX-License-Identifier: MIT
```

**Comment by benhoff** [comment]
@nmanovic licensing in the python files? Or document in the readme file?

**Comment by nmanovic** [comment]
@benhoff , we add license terms into each file.

**Pull request merged**
