### PR TITLE
React UI: ReID algorithm

### PR DESCRIPTION
**Pull request by bsekachev**
### Motivation and context
The PR adds a feature from the old UI: **Re-Identification algorithm**

Screenshot from 2020-04-15 13-01-48
Screenshot from 2020-04-15 13-01-51
Screenshot from 2020-04-15 13-08-14

### Checklist

- [x] I have raised an issue to propose this change ([required](https://github.com/opencv/cvat/issues))
- [x] My issue has received approval from the maintainers
- [x] I've read the [CONTRIBUTION](https://github.com/opencv/cvat/blob/develop/CONTRIBUTING.md) guide
- [x] I have added description of my changes into [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
~~- [ ] I have updated the [documentation](
  https://github.com/opencv/cvat/blob/develop/README.md#documentation) accordingly~~
~~- [ ] I have added tests to cover my changes~~
- [x] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [x] I have updated the license header for each file (see an example below)

Related #1341

### CODE REVIEW

**Comment by bsekachev** [comment]
@ActiveChooN 

Mainly the feature is done (it works in base scenarios). I am going to test it deeper, that is the reason why it has WIP tag. You can already look at the PR also.

**Comment by LukeAI** [comment]
what's the underlying algorithm? do you have a link to a paper?

**Comment by LukeAI** [comment]
does it associate labelled data or does it label new data based on an already labelled track?

**Comment by nmanovic** [comment]
It is one of person-re-identification models from https://github.com/opencv/open_model_zoo/

**Pull request merged**
