### PR TITLE
Updated Python version in development-environment.md to 3.10 🐍

### PR DESCRIPTION
**Pull request by adkbbx**
### Motivation and context
 

I have updated minimum Python version in development environment.md from 3.9 to 3.10 which I think would be valuable for new contributors trying to set up the development environment locally on their systems. It resolves the issue #7522 .

### How has this been tested?

This is just an edit in the documentation.

### Checklist

- [x] I submit my changes into the `develop` branch
- [x] I have updated the documentation accordingly
- [x] I have linked related issues (see [GitHub docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.

### CODE REVIEW

**Comment by bsekachev** [comment]
Hello, thanks. 

Let's merge it. But I believe in general we just need to upgrade the guide for newer OS versions (e.g. at least for Ubuntu 22 or maybe even 24.04 when it is released.

**Review by bsekachev — APPROVED** [review]

**Comment by adkbbx** [comment]
Hello @bsekachev,

Thank you for reviewing the pull request and your feedback.  Regarding your suggestion to update to Ubuntu 22 or 24.04, I initially thought the environment used Ubuntu 18.04 due to its compatibility with the dependencies. But if you suggest updating the OS version to Ubuntu 22 or higher would be better I can do that for you in the documentation or should we stick with the current version itself for now?

Thank you for your guidance.

**Comment by bsekachev** [comment]
From my side, I would prefer to wait until Ubuntu 24.04.

**Comment by adkbbx** [comment]
Noted!

**Pull request merged**
