### PR TITLE
UI change frame optimization

### PR DESCRIPTION
**Pull request by PMazarovich**
### Motivation and context

Currently user have to delete current frame and enter needed one, then press enter.
With this change, when user click on InputNumber, this field automatically clears and user don't need to do it manually.

### How has this been tested?

It was tested manually

### Checklist

- [x] I submit my changes into the `develop` branch
- [ ] I have added a description of my changes into the [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] I have linked related issues (see [GitHub docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [ ] I have increased versions of npm packages if it is necessary
  ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
  [cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning),
  [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and
  [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.

### CODE REVIEW

**Comment by klakhov** [comment]
@PMazarovich Thanks for contribution! Can you please fix ESLint issues and add a line to [changelog](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md)?

**Comment by klakhov** [comment]
Also I think it would be good to add restoring frame number if new frame number is not provided by user.

**Comment by bsekachev** [comment]
@PMazarovich 

Could you please clarify motivation of this pull request?
Currently, when I delete a frame, it automatically goes to the new one:
test 2

If this checkbox in settings is disabled:
image

**Comment by PMazarovich** [comment]
@klakhov , I'll try to fix this
@bsekachev here is some screenshots of how this is used. It is not about deleted frames.
In second screenshot you may see, that InputNumber automatically clears, when user clicks on it. This is more convenient than deleting current frame number before inserting needed one
frst
scnd
thrd

**Comment by bsekachev** [comment]
@PMazarovich 

Okay, I see. Thank you for clarification.
But I would propose another solution because I do not really like this logic with ``null`` target frame. What's more it brings some not logic things like on this demo (we are on frame 10, click in, click out, start going next/previous and it setups 1, 2, etc.)

test 3. 

Finally this solution does not work with hotkey (~) which is used to focus the input field for a frame number.

I would suggest **when users focuses the element, CVAT selects its text automatically**, using built-in methods, for example:
image

Where ``temp2`` is an input element.  Of course it just raw proposal, need to wrap it somehow in React application. 

In the interface, we see like this when focused:
image

**Comment by PMazarovich** [comment]
@bsekachev , @klakhov requested changes are in place

**Comment by bsekachev** [comment]
@PMazarovich 

Great, thank you for the contribution!

**Review by bsekachev — APPROVED** [review]

**Pull request merged**
