### PR TITLE
Allow interactor to return multiple polygons

### LINKED ISSUE #5070: Allow interactor to return multiple polygons
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

I built a custom interactor similar to IOG, bbox + positive points + negative points, that is able to recognize more than one object in the bbox. 
I tried integrating my interactor with cvat by following the structure of the existing ones, and it works if in the [response call](https://github.com/opencv/cvat/blob/29702a801fec771e2436131e13e17e66623e5fba/serverless/openvino/dextr/nuclio/main.py#L23) I return only one polygon. If more than one polygon are returned, no polygons are displayed on the cvat interface.

If one Polygon is returned by the interactor:
image

If multiple Polygons are returned:
image

I tried returning polygons in the following formats:

- a list of polygons: 
```python
[
    [[x11, y11], [x21, y21], ... ], 
    [[x12, y12], [x22, y22], ... ]
]
```
- a list of dicts with the same structure as the detectors:
```python
[
    {
         "points": [[x11, y11], [x21, y21], ... ],
         "type": "polygon"
    },
   ...
]
```

### Expected Behaviour

When a list of polygons is returned by an interactor, all the polygons should be processed by the cvat interface.

### Current Behaviour

If a list of polygons is returned, none of them appear on the cvat interface.

### Possible Solution

Edit the [function that process the interactor response](https://github.com/opencv/cvat/blob/develop/cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/tools-control.tsx#L338-L402) to detect if there are multiple polygons and process each one of them.

### Steps to Reproduce (for bugs)

Not applicable.

### Context

In our application, the object we are tying to annotate can be very small and very close to each other. To ease the burden of the annotators, we wanted to build an interactor that is able to segment multiple objects in one run. This allows the annotators to choose a larger bounding box and add many positive / negative guiding points to automatically segment many small objects.

### Your Environment

- Git hash commit (`git log -1`): `d7560bbd39fec68f944515c2591dda74f3764b90`
- Docker version `docker version` (e.g. Docker 17.0.05): 

<details>

    Client: Docker Engine - Community
    Version:           20.10.17
    API version:       1.41
    Go version:        go1.17.11
    Git commit:        100c701
    Built:             Mon Jun  6 23:02:57 2022
    OS/Arch:           linux/amd64
    Context:           default
    Experimental:      true

    Server: Docker Engine - Community
    Engine:
    Version:          20.10.17
    API version:      1.41 (minimum version 1.12)
    Go version:       go1.17.11
    Git commit:       a89b842
    Built:            Mon Jun  6 23:01:03 2022
    OS/Arch:          linux/amd64
    Experimental:     false
    containerd:
    Version:          1.6.6
    GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
    runc:
    Version:          1.1.2
    GitCommit:        v1.1.2-0-ga916309
    docker-init:
    Version:          0.19.0
    GitCommit:        de40ad0

</details>

- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): `Linux dev-cvat 5.15.0-1019-aws **#23~20.04.1-Ubuntu**`
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    No logs appear.

### PR DESCRIPTION
**Pull request by simone-viozzi**
### Motivation and context

Fixes #5070 

- `ToolsControlComponent` now store `latestResponse` and `latestResult` as a list of polygons (`number[][][]`)
- Made it compatible with interactors that return a single polygon, wrapping the response into a list
- Add a way to preview all the polygons
- When the user confirms the interaction, create all the annotations

### Checklist

- [x] I submit my changes into the `develop` branch
- [ ] I have added a description of my changes into [CHANGELOG](https://github.com/cvat-ai/cvat/blob/develop/CHANGELOG.md) file
- [ ] I have updated the [documentation](
  https://github.com/cvat-ai/cvat/blob/develop/README.md#documentation) accordingly
- [ ] I have added tests to cover my changes
- [x] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [ ] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/cvat-ai/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/cvat-ai/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/cvat-ai/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/cvat-ai/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/cvat-ai/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.

### CODE REVIEW

**Comment by simone-viozzi** [comment]
Hi @bsekachev, what do you think about the implementation until now?

I tried to call `canvasInstance.interact` in a loop, but this didn't work, and the preview is broken right now (only show one of the polygons)

```ts
for (const polygon of this.interaction.latestResult) {
    if (polygon.length) {
        canvasInstance.interact({
            enabled: true,
            intermediateShape: {
                shapeType: ShapeType.POLYGON,
                points: polygon.flat(),
            },
            onChangeToolsBlockerState: this.onChangeToolsBlockerState,
        });
    }
}
```

Any advice on how to proceed?

**Comment by bsekachev** [comment]
Hi @simone-viozzi 

``canvasInstance.interact`` was designed to show exactly one shape.
If more are necessary, need to update the code in ``cvat-canvas/typescript/interactionHandler.ts`` in such way it will be able to display multiple polygons, and then need to pass all these polygons in one call of ``.interact()``. 

Also, could you please look at this patch? https://github.com/opencv/cvat/pull/4543
There masks are introduced, including ability to accept masks from interactors and detectors. Maybe it will help you with your use-case.

**Comment by bsekachev** [comment]
@simone-viozzi 

Sure, just give me some time to review. 
About tests, so, unfortunately we do not have any tests for serverless functions.

**Comment by bsekachev** [comment]
Hello, 

Sorry for delay. 
Now we are re-working this functionality
Moreover, since now interactors can return masks, I do not see real sense in returning many polygons. 

Anyway, thank you

**Pull request closed without merging**
