### PR TITLE
React UI: Batch of fixes

### PR DESCRIPTION
**Pull request by bsekachev**
Fix: issues with drawing (corner cases)
Fix: grid opacity doesn't work
Fix: putting shape out of canvas works wrong
Fix: reset zoom for images by default
Fix: selecting in grouping mode
Fix: selecting in panzoom mode
Fix: text for locked shapes aren't displayed
Fix: outside shapes can be activated
Fix: issues with code in ``cvat-ui/src/containers/annotation-page/standard-workspace/controls-side-bar/draw-shape-popover.tsx``
Fix: Disable tracks for polygons, polyshapes and points (because it isn't supported by server and algorithms can be changed in the future)

### CODE REVIEW

**Comment by ActiveChooN** [comment]
If you accidentally move shape out of the canvas it falls with such errors

canvas_bug


```
Uncaught Error: Canvas is busy. Action: drag
    at CanvasModelImpl.activate (canvasModel.ts:347)
    at CanvasImpl.activate (canvas.ts:97)
    at CanvasWrapperComponent.activateOnCanvas (canvas-wrapper.tsx:265)
    at CanvasWrapperComponent.componentDidUpdate (canvas-wrapper.tsx:152)
    at commitLifeCycles (react-dom.development.js:22084)
    at commitLayoutEffects (react-dom.development.js:25302)
    at HTMLUnknownElement.callCallback (react-dom.development.js:336)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:385)
    at invokeGuardedCallback (react-dom.development.js:440)
    at commitRootImpl (react-dom.development.js:25040)
react-dom.development.js:21810 The above error occurred in the <CanvasWrapperComponent> component:
    in CanvasWrapperComponent (created by CanvasWrapperContainer)
    in CanvasWrapperContainer (created by ConnectFunction)
    in ConnectFunction (created by StandardWorkspaceComponent)
    in section (created by BasicLayout)
    in BasicLayout (created by Context.Consumer)
    in Adapter (created by StandardWorkspaceComponent)
    in StandardWorkspaceComponent (created by AnnotationPageComponent)
    in section (created by BasicLayout)
    in BasicLayout (created by Context.Consumer)
    in Adapter (created by AnnotationPageComponent)
    in AnnotationPageComponent (created by AnnotationPageContainer)
    in AnnotationPageContainer (created by ConnectFunction)
    in ConnectFunction (created by Context.Consumer)
    in withRouter(Connect(AnnotationPageContainer)) (created by Context.Consumer)
    in Route (created by CVATApplication)
    in Switch (created by CVATApplication)
    in main (created by Basic)
    in Basic (created by Context.Consumer)
    in Adapter (created by CVATApplication)
    in section (created by BasicLayout)
    in BasicLayout (created by Context.Consumer)
    in Adapter (created by CVATApplication)
    in Router (created by BrowserRouter)
    in BrowserRouter (created by CVATApplication)
    in CVATApplication (created by reduxAppWrapper)
    in reduxAppWrapper (created by ConnectFunction)
    in ConnectFunction
    in Provider

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:21810
react-dom.development.js:12193 Uncaught Error: Canvas is busy. Action: drag
    at CanvasModelImpl.activate (canvasModel.ts:347)
    at CanvasImpl.activate (canvas.ts:97)
    at CanvasWrapperComponent.activateOnCanvas (canvas-wrapper.tsx:265)
    at CanvasWrapperComponent.componentDidUpdate (canvas-wrapper.tsx:152)
    at commitLifeCycles (react-dom.development.js:22084)
    at commitLayoutEffects (react-dom.development.js:25302)
    at HTMLUnknownElement.callCallback (react-dom.development.js:336)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:385)
    at invokeGuardedCallback (react-dom.development.js:440)
    at commitRootImpl (react-dom.development.js:25040)
```

**Comment by bsekachev** [comment]
@ActiveChooN 
It is one more bug that isn't related with this PR.
It is in develop also. 
Probably it's better to create a different PR for it.

**Comment by ActiveChooN** [comment]
@bsekachev 
Ok, other looks fine. Should i create an issue for this problem?

**Comment by bsekachev** [comment]
@ActiveChooN 

Yes, you can. 
Actually issue is not just moving a shape out of canvas.
It's need to do ``mouseover`` on an element in side panel during dragging a shape from the canvas.

**Pull request merged**
