### PR TITLE
React UI: Added button to reset color settings

### PR DESCRIPTION
**Pull request by bsekachev**
Screenshot from 2020-04-02 15-36-53

### CODE REVIEW

**Comment by bsekachev** [comment]
@ActiveChooN 

Hmm.. Is scale 100%?

**Comment by ActiveChooN** [comment]
@bsekachev 

> 
> 
> @ActiveChooN
> 
> Hmm.. Is scale 100%?

Yes, if you mean about browser scale
изображение

**Comment by bsekachev** [comment]
@ActiveChooN 

What about system scale in windows?

**Comment by ActiveChooN** [comment]
> 
> 
@bsekachev 

> @ActiveChooN 
> 
> What about system scale in windows?

изображение

**Comment by bsekachev** [comment]
@ActiveChooN 
What about the latest patch?

**Comment by bsekachev** [comment]
@ActiveChooN 

Try the fix above

**Comment by ActiveChooN** [comment]
@bsekachev, will it be ok to merge this PR, and open new issue about layout displaying?

**Comment by bsekachev** [comment]
> @bsekachev, will it be ok to merge this PR, and open new issue about layout displaying?
> 

Yes

**Pull request merged**
