### PR TITLE
fixed dump error after moving format files

### PR DESCRIPTION
**Pull request by azhavoro**

### CODE REVIEW

**Comment by zhiltsov-max** [comment]
Fixes the second problem in #1336.

**Comment by nmanovic** [comment]
@azhavoro , please add info about the fix into CHANGELOG.md

**Comment by zhiltsov-max** [comment]
@azhavoro, the issue still persists for **uploading** in the current beta.1 release.

**Comment by zhiltsov-max** [comment]
@azhavoro, I've got the issue in the current release "beta.1".

```
13:12:01 RQ worker 'rq:worker:d29d208c520e4454a2f7cfc2b0090d60' started, version 1.0
13:12:01 *** Listening on default...
13:13:58 default: cvat.apps.engine.annotation.load_task_data('1', <User: max>, '/tmp/cvat_1ium2syaw', <AnnotationLoader: AnnotationLoader object (COCO JSON 1.0)>) (max@/api/v1/tasks/1/annotations/upload)
13:13:58 FileNotFoundError: [Errno 2] No such file or directory: '/home/max/cvat/cvat/apps/annotation/coco.py'
Traceback (most recent call last):
  File "/home/max/cvat/.env/lib/python3.6/site-packages/rq/worker.py", line 812, in perform_job
    rv = job.perform()
  File "/home/max/cvat/.env/lib/python3.6/site-packages/rq/job.py", line 588, in perform
    self._result = self._execute()
  File "/home/max/cvat/.env/lib/python3.6/site-packages/rq/job.py", line 594, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/home/max/cvat/cvat/apps/engine/annotation.py", line 112, in load_task_data
    annotation.upload(filename, loader)
  File "/home/max/cvat/cvat/apps/engine/annotation.py", line 751, in upload
    source_code = open(os.path.join(settings.BASE_DIR, db_format.handler_file.name)).read()
FileNotFoundError: [Errno 2] No such file or directory: '/home/max/cvat/cvat/apps/annotation/coco.py'

Traceback (most recent call last):
  File "/home/max/cvat/.env/lib/python3.6/site-packages/rq/worker.py", line 812, in perform_job
    rv = job.perform()
  File "/home/max/cvat/.env/lib/python3.6/site-packages/rq/job.py", line 588, in perform
    self._result = self._execute()
  File "/home/max/cvat/.env/lib/python3.6/site-packages/rq/job.py", line 594, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/home/max/cvat/cvat/apps/engine/annotation.py", line 112, in load_task_data
    annotation.upload(filename, loader)
  File "/home/max/cvat/cvat/apps/engine/annotation.py", line 751, in upload
    source_code = open(os.path.join(settings.BASE_DIR, db_format.handler_file.name)).read()
FileNotFoundError: [Errno 2] No such file or directory: '/home/max/cvat/cvat/apps/annotation/coco.py'
13:22:59 default: cvat.apps.engine.annotation.dump_task_data('1', <User: max>, '/home/max/cvat/data/tasks/1/artifacts/t1.max.2020_04_17_13_22_59.json', <AnnotationDumper: AnnotationDumper object (COCO JSON 1.0)>, 'http', 'localhost:7000') (max@/api/v1/tasks/1/annotations/COCO JSON 1.0/t1)
13:22:59 default: Job OK (max@/api/v1/tasks/1/annotations/COCO JSON 1.0/t1)
13:22:59 Result is kept for 500 seconds

```

**Pull request merged**
