### PR TITLE
add link to create of many tasks from project page

### LINKED ISSUE #5000: Can't add multiple tasks in project
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

When creating an project, it is not possible to add multiple tasks (videos) to it from inside the project. It is however possible to do so by afterwards, go to tasks and then create multiple tasks and then link them in that view.

Screenshot 2022-09-27 at 11 54 50 AM

Screenshot 2022-09-27 at 11 57 14 AM

### Expected Behaviour

It should be possible to add multiple tasks from within the project so the user has a better and clearer user experience. 

### Current Behaviour

creates a single tasks when hitting the add button in a project

### Possible Solution

possibly create a button component that can be used in projects and tasks so that it stays synced when new features get added. 

### Steps to Reproduce (for bugs)

1. see images

### Context

confusing to user

### Your Environment

- Git hash commit (`git log -1`): 4f6e81eab354d29c548cb368d22a9dd1d8423b8b
- Docker version `docker version` (e.g. Docker 17.0.05): 20.10.17
- Are you using Docker Swarm or Kubernetes? no
- Operating System and version (e.g. Linux, Windows, MacOS): MacOS / Linux

### PR DESCRIPTION
**Pull request by AlexeyAlexeevXperienceAI**
### Motivation and context
Resolved #5000

### Checklist

- [ ] I submit my changes into the `develop` branch
- [ ] I have added a description of my changes into [CHANGELOG](https://github.com/cvat-ai/cvat/blob/develop/CHANGELOG.md) file
- [ ] I have updated the [documentation](
  https://github.com/cvat-ai/cvat/blob/develop/README.md#documentation) accordingly
- [ ] I have added tests to cover my changes
- [ ] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [ ] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/cvat-ai/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/cvat-ai/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/cvat-ai/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/cvat-ai/cvat/tree/develop/cvat-ui#versioning))

### License

- [ ] I submit _my code changes_ under the same [MIT License](
  https://github.com/cvat-ai/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.

### CODE REVIEW

**Comment by bsekachev** [comment]
Hi, @AlexeyAlexeevXperienceAI 

Let's keep UI consistent for tasks page and project page.

Now it is different. For tasks page is:
image

and for project page is:
image

**Comment by AlexeyAlexeevXperienceAI** [comment]
@bsekachev 
I added a dropdown to the project page. check again

**Comment by bsekachev** [comment]
Great @AlexeyAlexeevXperienceAI 

One more comment from my side. I believe ``Ok`` button should navigate to **project page** when tasks are created.
But now it navigates to **tasks page**. 
image

**Review by bsekachev — APPROVED** [review]

**Pull request merged**
