### PR TITLE
Task progress bar improvement

### PR DESCRIPTION
**Pull request by PMazarovich**
### Motivation and context

There is no way to know it is in validation except going inside the task itself. It can be tedious, just to check the status. 
With this improvement summary of job stages is revealed on task itself.

### How has this been tested?

It was tested manually

### Checklist

- [x] I submit my changes into the `develop` branch
- [ ] I have added a description of my changes into the [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] I have linked related issues (see [GitHub docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [ ] I have increased versions of npm packages if it is necessary
  ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
  [cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning),
  [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and
  [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))

Example:

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.

### CODE REVIEW

**Comment by zhiltsov-max** [comment]
Hi, could you please check with the latest develop? This may be broken, because server responses about jobs were changed recently.

**Comment by PMazarovich** [comment]
@zhiltsov-max Hello, done.
It still works

**Comment by nmanovic** [comment]
@PMazarovich , could you please resolve the conflicts? Also, we have merged a big PR with REST API changes. Could you please check that your logic works?

**Comment by zhiltsov-max** [comment]
@bsekachev, sure.

**Comment by PMazarovich** [comment]
@zhiltsov-max  @nmanovic @bsekachev ,Hello!
Should I improve this PR some way so it will be merged?

**Comment by PMazarovich** [comment]
@zhiltsov-max ok, thanks for the info

**Comment by zhiltsov-max** [comment]
@PMazarovich, please update the PR.

**Comment by PMazarovich** [comment]
@zhiltsov-max done

**Comment by zhiltsov-max** [comment]
@bsekachev, could you review please?

**Comment by bsekachev** [comment]
image

**Review by bsekachev — APPROVED** [review]

**Pull request merged**
