### PR TITLE
cvat (django): Add optional configuration for Redis password

### PR DESCRIPTION
**Pull request by ljades**
Addresses: https://github.com/openvinotoolkit/cvat/issues/3133

### Motivation and context

This will allow users who require their Redis cache deployment to have a password, for security purposes, to instantiate a password-protected Redis and have their CVAT server django container connect to it properly.

### How has this been tested?

We've been running a CVAT instance on our Kubernetes cluster (caveat: v1.6.0, but I also made adjustments to match the current version of the production.py file) for the past year and it's been functioning as expected. Our Redis instance is configured with a password and the django container can properly connect to it.

### Checklist

- [x] I submit my changes into the `develop` branch
- [x] I have added a description of my changes into [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
- [ ] I have updated the [documentation](
  https://github.com/opencv/cvat/blob/develop/README.md#documentation) accordingly
- [ ] I have added tests to cover my changes
- [x] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [x] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [x] I have updated the license header for each file (see an example below)

```python
# Copyright (C) 2022 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

### CODE REVIEW

**Comment by ljades** [comment]
Hi! Questions about my PR:

1. Is adding documentation required for this PR? There is no documentation on custom redis configuration that I was able to find in the first place, so I couldn't find a spot to add this to. If I should, where do I add it to?
2. Is there a way of adding unit tests to a change in this production.py file? Or are we find without them as well?

**Comment by Marishka17** [comment]
Hi, @ljades, thanks for the contribution! Are you still going to contribute to us? If so, could you please resolve conflicts in this PR?

**Comment by ljades** [comment]
> Hi, @ljades, thanks for the contribution! Are you still going to contribute to us? If so, could you please resolve conflicts in this PR?

Hi @Marishka17, yes I still plan on it! I'm a bit busy this week though, so many not happen until next week or a bit later.

This merge conflict wasn't a thing until recently though when another PR was merged. It would be helpful if my other questions could be addressed and the rest of the PR reviewed in the meantime, since CHANGELOG.md conflicts could happen at virtually any time, even if I were to resolve.

**Comment by nmanovic** [comment]
@ljades , thanks for the contribution. I believe we need the change not only for production. Also, we have so many env variables in our settings, that need to understand how to organize and document them. I will close the PR for now.

**Pull request closed without merging**
