### PR TITLE
Add test code for cli upload function

### PR DESCRIPTION
**Pull request by ncianeo**
@nmanovic
Thank you for letting me contribute to this great project!
As you asked in #958, I added a test code for the upload function.
Since I am not used to django nor unittest, I am not sure whether the test code will work or not.

### CODE REVIEW

**Comment by nmanovic** [comment]
@ncianeo ,

Thanks for your time to contribute! Could you please sync your repo with upstream? It seems you submit the same changes + test. As results of the fact there are merge conflicts.

**Comment by ncianeo** [comment]
@nmanovic ,
I synced my repo with upstream and added new commit that resolves merge conflicts.

**Comment by nmanovic** [comment]
@ncianeo , thanks for your great contribution into the product! Your PRs helped many people in our community.

**Comment by ncianeo** [comment]
@nmanovic , Thanks! I am very pleased to hear that!

**Pull request merged**
