### PR TITLE
Fix the missing env variable issue

### LINKED ISSUE #5448: Unable to create a new task
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Expected Behaviour

A task will be successfully created once the data is uploaded and clicked `save & continue`.

### Current Behaviour

I follow an installation manual using Docker by `docker-compose up`. It successfully builds the software and I can access it there via localhost:8080. But I couldn't finish creating a task as I stuck after I uploaded a video and save&continue. I bet there might be a problem with the `cvat_worker_low` node (an error message is below). 
```
cvat_worker_low       | Error: Format string '%(ENV_HOME)s/wait-for-it.sh %(ENV_CVAT_REDIS_HOST)s:6379 -t 0 -- bash -ic " \\\nif [ \\"%(ENV_CVAT_DEBUG_ENABLED)s\\" = \'yes\' ]; then \\\n_DEBUG_CMD=\\"-m debugpy --listen 0.0.0.0:%(ENV_CVAT_DEBUG_PORT)s\\";\nelse\n_DEBUG_CMD=\\"\\";\nfi && \\\n\\\nexec python3 ${_DEBUG_CMD} %(ENV_HOME)s/manage.py rqworker -v 3 low \\\n"' for 'program:rqworker_low.command' contains names ('ENV_CVAT_DEBUG_ENABLED') which cannot be expanded. Available names: ENV_CVAT_DEBUG_PORT, ENV_CVAT_POSTGRES_HOST, ENV_CVAT_REDIS_HOST, ENV_DJANGO_CONFIGURATION, ENV_HOME, ENV_HOSTNAME, ENV_LANG, ENV_LC_ALL, ENV_NUMPROCS, ENV_PATH, ENV_TERM, ENV_TZ, ENV_USER, ENV_http_proxy, ENV_https_proxy, ENV_no_proxy, ENV_socks_proxy, group_name, here, host_node_name, process_num, program_name in section 'program:rqworker_low' (file: 'supervisord/worker.low.conf')
```
Also, the screenshots of logs after I run `docker-compose up` are shown below.
Screen Shot 2022-12-11 at 12 50 44
Screen Shot 2022-12-11 at 12 50 55

### Steps to Reproduce (for bugs)

1. Clone the latest `cvan` repository.
2. Run `docker-compose up`

### Context

This issue affects me to create a new task to start annotation...

### Your Environment

- Git hash commit (`git log -1`): a3b4f97f9a806edbce5905ec1250892c5a70774e
- Docker version `docker version` (e.g. Docker 17.0.05): Docker 4.13.1
- Are you using Docker Swarm or Kubernetes?: No
- Operating System and version (e.g. Linux, Windows, MacOS): MacOS Monterey, MacBook Pro (13-inch, M1, 2020)

### PR DESCRIPTION
**Pull request by zhiltsov-max**
### Motivation and context

Fixes #5448, #5453, #5457

- Relaxed env var requirements in the images, no mandatory ones
- RQ workers now use a custom python class for remote debugging
- Factored out common remote debugging implementation

### Checklist

- [ ] I submit my changes into the `develop` branch
- [ ] I have added a description of my changes into [CHANGELOG](https://github.com/cvat-ai/cvat/blob/develop/CHANGELOG.md) file
- [ ] I have updated the [documentation](
  https://github.com/cvat-ai/cvat/blob/develop/README.md#documentation) accordingly
- [ ] I have added tests to cover my changes
- [ ] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [ ] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/cvat-ai/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/cvat-ai/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/cvat-ai/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/cvat-ai/cvat/tree/develop/cvat-ui#versioning))

### License

- [ ] I submit _my code changes_ under the same [MIT License](
  https://github.com/cvat-ai/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.

### CODE REVIEW

**Comment by knidarkness** [comment]
Is there any chance for this to be merged soon? We are blocked by the issue this PR solves, yet we need webhooks support, which is not yet in the `master` branch, so I was wondering if there's something blocking this PR. 

Thanks

**Review by nmanovic — COMMENTED** [review]
LGTM

**Comment by DeepBlue27** [comment]
this fixed nothing :\ the problem persist

**Comment by zhiltsov-max** [comment]
@DeepBlue27 , @knidarkness 
Hi, please run `docker pull cvat/server:dev` and restart the containers with `docker-compose up -d` to update your local Docker images to the fixed version. If you're using custom images, please rebuild them with `docker-compose -f docker-compose.yml -f docker-compose.dev.yml build` and restart the containers.

**Pull request merged**
