### PR TITLE
Various improvements to the SDK generation process

### PR DESCRIPTION
**Pull request by SpecLad**
See the commit messages for details.

### Motivation and context

My main motivation was that I was going to add documentation on the PyTorch adapter, and I didn't want to update the redundant README templates, so I removed those. The rest of the changes are just for fixing various minor issues that I experienced while working with the generator.

### How has this been tested?

By running `generate.sh`.

### Checklist

- [x] I submit my changes into the `develop` branch
- ~~[ ] I have added a description of my changes into the [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file~~
- ~~[ ] I have updated the documentation accordingly~~
- ~~[ ] I have added tests to cover my changes~~
- ~~[ ] I have linked related issues (see [GitHub docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))~~
- ~~[ ] I have increased versions of npm packages if it is necessary
  ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
  [cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning),
  [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and
  [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))~~

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.

### CODE REVIEW

**Comment by zhiltsov-max** [comment]
Please update `.gitignore` if you wish to move the files you're moving. But probably, the idea was to avoid having anything that can be overridden by the script in the `cvat-sdk/` directory, and to avoid cherry-picking ignores for separate files. Otherwise, if the script fails on some step, it can be hard to fix the user files in the directory.

**Comment by SpecLad** [comment]
> Please update .gitignore if you wish to move the files you're moving. 

Sure; done.

> But probably, the idea was to avoid having anything that can be overridden by the script in the cvat-sdk/ directory, and to avoid cherry-picking ignores for separate files. Otherwise, if the script fails on some step, it can be hard to fix the user files in the directory.

Since I added `MANIFEST.in` and `README.md` into `.openapi-generator-ignore`, that shouldn't be a problem.

**Comment by SpecLad** [comment]
Added another fix.

**Review by zhiltsov-max — APPROVED** [review]
Please adjust `site/content/en/docs/api_sdk/sdk/developer-guide.md` to reflect the new workflow changes, if any.

**Comment by SpecLad** [comment]
> Please adjust `site/content/en/docs/api_sdk/sdk/developer-guide.md` to reflect the new workflow changes, if any.

I checked, but it doesn't seem like any changes are needed.

**Comment by SpecLad** [comment]
@nmanovic Could you merge this?

**Pull request merged**
