### PR TITLE
React UI: Fixed escape in draw

### PR DESCRIPTION
**Pull request by bsekachev**

### CODE REVIEW

**Comment by nmanovic** [comment]
@bsekachev , let's add the info into CHANGELOG.md

**Comment by nmanovic** [comment]
@ActiveChooN , could you please review the PR?

**Comment by ActiveChooN** [comment]
@bsekachev, are there any other options than clicking shape icon to complete drawing?

**Comment by bsekachev** [comment]
@ActiveChooN 

``N`` shortcut

**Pull request merged**
