### PR TITLE
TS Module from CVAT-Canvas

### PR DESCRIPTION
**Pull request by bsekachev**
- Importing cvat-canvas as a module in TS
- Updated documentation
- Updated configs
- A couple of fixes in code

### CODE REVIEW

**Comment by nmanovic** [comment]
@zankevich , could you please review?

**Comment by zankevich** [comment]
> @zankevich , could you please review?

Sure

**Comment by nmanovic** [comment]
@zankevich , awesome. Please let me know when the PR is ready to merge.

**Comment by bsekachev** [comment]
@zankevich 
I think we are not in a hurry with this.

**Comment by nmanovic** [comment]
@zankevich , I have merged. Don't hesitate to send us any comments after that.

**Pull request merged**
