### PR TITLE
Fixed unstable e2e restore tests

### LINKED ISSUE #4995: Unstable Cypress test
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Current Behaviour
Here is two workflow runs from one commit hash:
https://github.com/opencv/cvat/actions/runs/3101423840
https://github.com/opencv/cvat/actions/runs/3101423840/attempts/1

As we can see for the same version of CVAT test `actions_projects_models/case_114_backup_restore_project.js` can be as red as green.                                                  

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### PR DESCRIPTION
**Pull request by klakhov**
### Motivation and context

Resolved #4995

The problem with restore tests arises when network runs slow, which can happen from time to time. After backup was uploaded tests were checking for restoring status. If its in progress, server returned `202`, if it ended server returned `201`. When network is fast enough `202` is returned, and if its slow, backup restore is ended already which leads to `201` response. Hence we need to make waiting for `202` response optional.

### Checklist

- [ ] I submit my changes into the `develop` branch
- [ ] I have added a description of my changes into [CHANGELOG](https://github.com/cvat-ai/cvat/blob/develop/CHANGELOG.md) file
- [ ] I have updated the [documentation](
  https://github.com/cvat-ai/cvat/blob/develop/README.md#documentation) accordingly
- [ ] I have added tests to cover my changes
- [ ] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [ ] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/cvat-ai/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/cvat-ai/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/cvat-ai/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/cvat-ai/cvat/tree/develop/cvat-ui#versioning))

### License

- [ ] I submit _my code changes_ under the same [MIT License](
  https://github.com/cvat-ai/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.

### CODE REVIEW

**Comment by klakhov** [comment]
@bsekachev Could you look on this fix?

**Review by bsekachev — APPROVED** [review]

**Pull request merged**
