### PR TITLE
ADD cvat-cli-csv

### PR DESCRIPTION
**Pull request by talhabacak**
### Checklist

- [x ] I submit my changes into the `develop` branch
- [ ] I have added a description of my changes into [CHANGELOG](https://github.com/cvat-ai/cvat/blob/develop/CHANGELOG.md) file
- [ ] I have updated the [documentation](
  https://github.com/cvat-ai/cvat/blob/develop/README.md#documentation) accordingly
- [ ] I have added tests to cover my changes
- [ ] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [ ] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/cvat-ai/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/cvat-ai/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/cvat-ai/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/cvat-ai/cvat/tree/develop/cvat-ui#versioning))

### License

- [ ] I submit _my code changes_ under the same [MIT License](
  https://github.com/cvat-ai/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.

### CODE REVIEW

**Comment by talhabacak** [comment]
add client

**Comment by zhiltsov-max** [comment]
Hi, please describe this PR functionality.

**Comment by nmanovic** [comment]
@talhabacak , thanks for the contribution. I like the idea to use CLI and CSV file to work with tasks on a CVAT instance. But I don't think we need a separate script for that. We need to integrate the functionality into our new [cvat-cli](https://github.com/opencv/cvat/tree/develop/cvat-cli) tool. Could you please work with @zhiltsov-max to integrate the feature into the offical CLI page? It is going to be a complex and non-trivial process.

**Comment by talhabacak** [comment]
> @talhabacak , thanks for the contribution. I like the idea to use CLI and CSV file to work with tasks on a CVAT instance. But I don't think we need a separate script for that. We need to integrate the functionality into our new [cvat-cli](https://github.com/opencv/cvat/tree/develop/cvat-cli) tool. Could you please work with @zhiltsov-max to integrate the feature into the offical CLI page? It is going to be a complex and non-trivial process.

@nmanovic @zhiltsov-max , thank you for your thoughts. Waiting for your directions.

**Comment by nmanovic** [comment]
@talhabacak , could you please look at our CLI and propose a solution? Don't wait a direction. Propose and discuss.

**Comment by nmanovic** [comment]
@talhabacak , I will close the PR. Don't hesitate to reopen it as soon as you have time to improve it.

**Pull request closed without merging**
