### PR TITLE
Fixes some serverless functions (HRNET, IOG, f-BRS)

### PR DESCRIPTION
**Pull request by amteusch**
### Motivation and context
Fixes https://github.com/opencv/cvat/issues/4736, and also includes a fix for HRNET from @IuliuNovac in https://github.com/opencv/cvat/issues/4900. Some serverless functions (IOG, f-BRS) were downloading weights from Google Drive, but Google Drive changed and weights were not downloading properly, this should address that. Also updates the yaml files for a few serverless functions that had outdated or incompatible versions of python, opencv, etc. There might be a better way to fix these yamls but this is simply how I got them working and figured it's better than nothing.

### How has this been tested?

Tested the serverless functions running locally on Ubuntu 20.04.5. They seemed to work fine, which is better than the current state of the repo, but I'm not sure if there is any performance decrease relative to when they worked before.

### Checklist

- [x] I submit my changes into the `develop` branch
- [x] I have added a description of my changes into [CHANGELOG](https://github.com/cvat-ai/cvat/blob/develop/CHANGELOG.md) file
- ~~[ ] I have updated the [documentation](
  https://github.com/cvat-ai/cvat/blob/develop/README.md#documentation) accordingly~~
- [ ] I have added tests to cover my changes
- [x] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- ~~[ ] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/cvat-ai/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/cvat-ai/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/cvat-ai/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/cvat-ai/cvat/tree/develop/cvat-ui#versioning))~~

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/cvat-ai/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.

### CODE REVIEW

**Comment by amteusch** [comment]
@yasakova-anastasia @bsekachev I see some of these changes made it in on another pull request, any way we can get this HRNET change too?

**Comment by bsekachev** [comment]
@yasakova-anastasia 

Could you please check HRNet?

**Comment by yasakova-anastasia** [comment]
> Could you please check HRNet?


Yes, HRNet is not working. These changes solve this problem

**Comment by bsekachev** [comment]
@amteusch 

Thank you for the contribution! :)

**Pull request merged**
