### PR TITLE
Update base.txt

### PR DESCRIPTION
**Pull request by pziewiec**
required gitdb in version 0.6.4

### CODE REVIEW

**Comment by nmanovic** [comment]
@pziewiec , what is the problem? We don't use GitDB directly. Why do we need the change?

**Comment by pziewiec** [comment]
docker-compose build doesnt work now

**Comment by nmanovic** [comment]
@pziewiec , a similar problem was fixed recently: https://github.com/opencv/cvat/issues/1152. Is it a new issue?

**Comment by pziewiec** [comment]
You right - the same problem

**Pull request closed without merging**
