### PR TITLE
Allow slashes in export filename

### PR DESCRIPTION
**Pull request by klakhov**
### Checklist

- [ ] I submit my changes into the `develop` branch
- [ ] I have added a description of my changes into the [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] I have linked related issues (see [GitHub docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [ ] I have increased versions of npm packages if it is necessary
  ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
  [cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning),
  [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and
  [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))

### License

- [ ] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.

### CODE REVIEW

**Comment by bsekachev** [comment]
What if task name something like `` test task /../../.. `` or ``/root/``?)

**Comment by klakhov** [comment]
If `custom_name` contains slashes `sendfile` from django replaces them with `_`, so everything is ok with local downloads.
But we need to check cloud storages.

**Comment by bsekachev** [comment]
@klakhov 

The question not about ``sendfile``, the question is about CVAT internal filesystem. Because before sendfile works, the file initially created within CVAT container.

**Comment by klakhov** [comment]
File initially created within CVAT container has nothing to do with filename provided by user.
[`cvat/apps/dataset_manager/views.py`](https://github.com/opencv/cvat/blob/develop/cvat/apps/dataset_manager/views.py#L65-L71):
```
        cache_dir = get_export_cache_dir(db_instance)

        exporter = EXPORT_FORMATS[dst_format]
        output_base = '%s_%s' % ('dataset' if save_images else 'annotations',
            make_file_name(to_snake_case(dst_format)))
        output_path = '%s.%s' % (output_base, exporter.EXT)
        output_path = osp.join(cache_dir, output_path)
```
It is only used as final filename which is provided to user (attachment_filename)

- In case of LOCAL export, Django `sendfile` validates path and replaces all `/` with `_`
- In case of CLOUD_STORAGE export, if path is correct `cat/dog/archive.zip`, feature works as expected. Using relative paths seems to be prohibited. If path contains `../../`, there will be an error. For example: 
```
boto3.exceptions.S3UploadFailedError: Failed to upload /home/kirill/projects/cvat/data/tasks/12/export_cache/task_backup.zip to tmp/car/dog/../a.zip: An error occurred (XMinioInvalidResourceName) when calling the PutObject operation: Resource name contains bad components such as ".." or ".".
```

**Pull request merged**
