### PR TITLE
Fix new tracker edit

### LINKED ISSUE #918: Edit Issue tracker
When change “Issue Tracking”, text “not specified” remains in the editing field. It would be more convenient if field for editing became empty (if link to issue tracking not specified).

Edit issue tracker

### PR DESCRIPTION
**Pull request by mmarkelov**
Fix #918 

As a workaround:

Clicking on "Edit" button will clear textarea.

1. If validation was fallen it will reset text to placeholder
2. Otherwise it will update text to input

I suppose it will be better to select all of text by clicking, but I suppose it will be not so easy to do with Antd Text implementation

### CODE REVIEW

**Comment by bsekachev** [comment]
@mmarkelov 

Hi, thanks for PR.
Unfortunately this solution doesn't work properly in any case. 
For example when I started editing and press Esc button, the edit mode closing and the field became empty.

**Comment by mmarkelov** [comment]
@bsekachev I'll take a look on this case

**Comment by mmarkelov** [comment]
@bsekachev unfortunately there is no method to catch end of editing of editable text right now. I suppose I can add this functionality to antd library, and fix this case

**Comment by bsekachev** [comment]
@mmarkelov 

It looks like too hard way to fix such a minor issue.
I'll think how we can get around the problem (for example with combination of two elements like <Text /> and <Input />)

**Comment by bsekachev** [comment]
@mmarkelov 

Let's close this PR till we have found a robust solution

**Pull request closed without merging**
