### PR TITLE
Allow trailing slashes in SDK client url

### LINKED ISSUE #5046: An additional slash at the end of the hostname makes some operations unworkable
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

An additional slash at the end of the hostname makes some operations unworkable.

### Current Behaviour

Using some operations from high-level API does not work when an additional slash at the end of the hostname is added. For example:
- download_backup
- export_dataset
- create_task_from_data

However, other operations like downloading independent images (download_frames) or getting information about projects or tasks work properly.

### Steps to Reproduce (for bugs)

Using the following code, having a slash at the end of the hostname, can be used to reproduce the error

```
from cvat_sdk import make_client, models
from cvat_sdk.core.proxies.tasks import ResourceType, Task

with make_client(host="http://localhost:8080/") as client:
    # Authorize using the basic auth
    client.login(('user', 'password'))

    # Models are used the same way as in the layer 1
    task_spec = {
        "name": "example task 2",
        "labels": [
            {
                "name": "car",
                "color": "#ff00ff",
                "attributes": [
                    {
                        "name": "a",
                        "mutable": True,
                        "input_type": "number",
                        "default_value": "5",
                        "values": ["4", "5", "6"],
                    }
                ],
            }
        ]
    }
    task = client.tasks.create_from_data(
        spec=task_spec,
        resource_type=ResourceType.LOCAL,
        resources=["image00200.png", "image01000.png"],
    )
```

### Context
This is a minor bug that led me to try many other things before I saw where the problem was. The solution should be simple and I believe it could avoid a lot of headaches.

### Your Environment
- Git hash commit: ba4175bf5b4467bf0fbf89a3fd645cceef7f7c23
- Docker version `docker version`: 19.03.13-ce
- Operating System and version: Linux (AWS EC2 Amazon Linux)

### PR DESCRIPTION
**Pull request by zhiltsov-max**
### Motivation and context

Closes #5046 

- Allowed trailing slashes in `Client(url=)` and `make_client(host=)` of CVAT SDK

### Checklist

- [ ] I submit my changes into the `develop` branch
- [ ] I have added a description of my changes into [CHANGELOG](https://github.com/cvat-ai/cvat/blob/develop/CHANGELOG.md) file
- [ ] I have updated the [documentation](
  https://github.com/cvat-ai/cvat/blob/develop/README.md#documentation) accordingly
- [ ] I have added tests to cover my changes
- [ ] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [ ] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/cvat-ai/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/cvat-ai/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/cvat-ai/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/cvat-ai/cvat/tree/develop/cvat-ui#versioning))

### License

- [ ] I submit _my code changes_ under the same [MIT License](
  https://github.com/cvat-ai/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.

### CODE REVIEW

**Comment by SpecLad** [comment]
For URLs this makes sense, but I don't think we should be doing this for hosts. Slashes are not valid in host names.

**Comment by zhiltsov-max** [comment]
> Slashes are not valid in host names.

Hm, I don't think the majority of users know about this, and even it they do, it's still very easy to make this mistake.

**Review by SpecLad — APPROVED** [review]
OK, it looks like the `host` parameter basically already accepts full URLs, so might as well.

**Comment by zhiltsov-max** [comment]
@nmanovic , this PR is ready for merging.

**Pull request merged**
