### PR TITLE
helm chart and gitignore fixes

### LINKED ISSUE #4651: Helm Chart minor problems
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

### Current Behaviour
Right now commit to helm chart broke the way postgresql secret was supposed to work with external db, and replaced it with constants in deployment for every installation except bundled postgresql chart from bitnami
изображение

### Possible Solution
we should revert that and also add rules.tar.gz to .gitignore 
I will try to do it myself when I will have time for that

### Context
Right now my installation will be  broken on update

### Your Environment
k8s, helm

### PR DESCRIPTION
**Pull request by Keramblock**
### Motivation and context
fixes #4651 

### How has this been tested?
on my k8s with external db

### Checklist

- [x] I submit my changes into the `develop` branch
- [x] I have added a description of my changes into [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
- [x] I have updated the [documentation](
  https://github.com/opencv/cvat/blob/develop/README.md#documentation) accordingly
- [x] I have added tests to cover my changes
- [x] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [x] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.
- [x] I have updated the license header for each file (see an example below)

```python
# Copyright (C) 2022 Intel Corporation
#
# SPDX-License-Identifier: MIT
```

### CODE REVIEW

**Comment by Keramblock** [comment]
@nmanovic sorry for bothering you, but could you please help with this pr?

**Comment by nmanovic** [comment]
@Keramblock , unfortunately I cannot at the moment. I hope it will be changed in the nearst future.

Please send your questions and complains to https://community.intel.com/t5/Intel-Distribution-of-OpenVINO/bd-p/distribution-openvino-toolkit forum. I hope that they should help.

**Comment by Keramblock** [comment]
ok, thank you

**Comment by Keramblock** [comment]
Is anybody alive here?

**Comment by nmanovic** [comment]
@Keramblock , could you please resolve merge conflicts?

**Comment by Keramblock** [comment]
@nmanovic For some reason @azhavoro just hardcoded unnecessary components(like traefic) and minikube configuration to chart defaults. Right now I dont understand why that happened6 because I dont see any reasons to force everybody to use traefik(WHY?) and minikube(should I host cvat on my notebook instead of AKS or GKE now?). And because I cant understand such changes - I cannot merge with them. 

P.S. Actually I think that is a mistake, that should be a part of user configuration, not a predefined defaults by vendor.

**Comment by Keramblock** [comment]
Here is some examples of configuration, that are not suitable for my use case at all: 
Screenshot 2022-09-07 at 14 02 14
Why traefik?  Currently I am using istio and nginx for all my infra, why should I rewrite all of this just for one product? Is it ok to force every user for such a change?

Screenshot 2022-09-07 at 14 03 11
Not everybody using ingress, not everybody using them on local domain, not everybody using it with traefik

изображение
Even if you are ok with forcing everybody to use traefik - installing it with cvat is a dependency of the specific chart is a bad idea. It will install traefik with every copy of cvat, so 3 cvats means 3 traefics on the cluster. 

I think that for opensource solution it is better to be agile and permit any kind of infra user wants to use and not force him to use that specific one from the box.

Also I do not sure that everybody want to use serverless functions and etc and as I could see, that there is 4 replicas now in different deployments of the same app instead of 1 that was before. That is 4 time more resources wasted, so I suggest to use flag to disable that by default.

**Comment by Keramblock** [comment]
This PR, that I have created 3 months ago - also was removing some hardcoded stuff from chart inflicted by previous contribution. I am not sure if that is ok to ask, but if you need maintainer for the helm chart - I could help you with that. Also if you need any help with support some specific configuration without hardcoding it for everybody else - I could help, if you want me too.

**Comment by nmanovic** [comment]
@azhavoro , could you please comment?

**Comment by nmanovic** [comment]
@Keramblock , we will be happy if you can help us wth helm chart. Just make appropriate changes and we will quicly review and merge.

**Comment by Keramblock** [comment]
I think, that it is too outdated right now, will open new one, if I will have any proposals to improve. Thank you!

**Pull request closed without merging**
