### PR TITLE
Setup nuclio timeout

### PR DESCRIPTION
**Pull request by PMazarovich**
### Motivation and context

See these several issues. They are connected to each other in some way. 
The thing is that nuclio has a default timeout of 1 minute. With this change we can force nuclio dashboard not to terminate the connection.
https://github.com/nuclio/nuclio/issues/3016
https://github.com/opencv/cvat/issues/3301
https://github.com/opencv/cvat/issues/6041

### Checklist

- [x] I submit my changes into the `develop` branch
- [ ] I have added a description of my changes into the [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] I have linked related issues (see [GitHub docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [ ] I have increased versions of npm packages if it is necessary
  ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
  [cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning),
  [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and
  [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.

### CODE REVIEW

**Comment by PMazarovich** [comment]
Moreover, if you have nuclio deployed as a, let's say, "monolith" with all functions on the same machine, you'll have another problem with gateway timeout and 504 error. 
This can be fixed by creating custom nuclio image with this small addition in nginx.conf
```
proxy_read_timeout 600;
proxy_connect_timeout 600;
proxy_send_timeout 600;

```

**Comment by nmanovic** [comment]
@PMazarovich , thank you for the contribution.

**Review by nmanovic — APPROVED** [review]
LGTM

**Comment by patcharees** [comment]
> Moreover, if you have nuclio deployed as a, let's say, "monolith" with all functions on the same machine, you'll have another problem with gateway timeout and 504 error. This can be fixed by creating custom nuclio-dashboard image with this small addition in nginx.conf
> 
> ```
> proxy_read_timeout 600;
> proxy_connect_timeout 600;
> proxy_send_timeout 600;
> ```

@PMazarovich I am having the problem. Can you please explain more?

**Comment by patcharees** [comment]
Hi @PMazarovich 

I got the code updated which set 'X-Nuclio-Invoke-Timeout': '600s'. I created custom nuclio dashboard which modifed nginx.conf as

proxy_read_timeout 600;
proxy_connect_timeout 600;
proxy_send_timeout 600;

But I still got error 504 gateway timeout when I use AI tool for detection. From docker logs, the deploy function sent response back, but it took long time as my image is very big.

Any ideas, what am I missing?

Thanks in advance

**Comment by patcharees** [comment]
I found suggestion from [https://stackoverflow.com/questions/68446927/cvat-call-to-nuclio-function-for-detector-times-out-after-60-seconds?fbclid=IwAR02iybvbHCNlH0mu1lp5VwteaQsvNjbiUWlA-4ewK-jMeUOhKm9GWwcI0o]

and actually fixed my problem.

**Pull request merged**
