### PR TITLE
video_name in database and dumped file for interpolation mode

### PR DESCRIPTION
**Pull request by edumotya**
Hi @BrunoLansacSBD , @nmanovic ,

I have opened a pull request that fixes issue #56.

### CODE REVIEW

**Comment by bsekachev** [comment]
@edumotya 

Hi, thank you for your PR. I have several issues here. 

First of all, I see you use new field "video_name", but I don't see any django migrations here. Currently the Task model doesn't consist this field. 
Secondly, answering your question, CVAT doesn't support several videos for a single task. 
Furthermore, I believe the code should be placed in the function "_save_task_to_db", not "make_image_meta_cache". 

Finally, in my opinion, CVAT is unified tool and we should strive to unification. More specific, it would be great to try find some common solution. Not only for a video. Maybe @nmanovic will disagree with me.

**Comment by nmanovic** [comment]
@edumotya , We don't need `video_name` field. Please look at Video and Image models. They contain all necessary information.

- https://github.com/opencv/cvat/blob/a5a9b0a0192fc4a75279563b0ba6579f07db3498/cvat/apps/engine/models.py#L128
- https://github.com/opencv/cvat/blob/a5a9b0a0192fc4a75279563b0ba6579f07db3498/cvat/apps/engine/models.py#L140

**Comment by edumotya** [comment]
Hi @bsekachev I agree with you, CVAT needs a generic solution. Therefore,

1. The new field should be named "source" like in annotation mode. Do you agree?
2. I placed the code in "make_image_meta_cache" to be consistent with the annotation mode analogous code [1]. Anyway, both codes (original annotation mode code [1] and my PR for interpolation mode [2])  are workarounds. As @nmanovic pointed out we don't need video_name field, but we don't need neither to extract the image paths walking the uploads folder [2], they both should be extracted from either Video or Image db models. The issue is that, as far as I know, _save_task_to_db/make_image_meta_cache do not have access neither to the Video nor Image models, only to the Task model, which does not keep the information of the original video path, it only keeps the extracted frame paths. So, how can I access to the Video model object from _save_task_to_db?

[1] make_image_meta_cache for annotation mode: https://github.com/opencv/cvat/blob/bfc9f8e5d81bd1662fea4a0a95ce04e7ec366341/cvat/apps/engine/task.py#L91-L95

[2] This PR make_image_meta_cache for interpolation mode: https://github.com/opencv/cvat/blob/bfc9f8e5d81bd1662fea4a0a95ce04e7ec366341/cvat/apps/engine/task.py#L106-L110

I haven't gone very deep into the code, so I apologise if i'm missing something obvious...

What do you propose?

**Comment by nmanovic** [comment]
@edumotya , the main problem here is `make_image_meta_cache(db_task)` is obsolete. It should be removed. Previously we created a special file which contained information about images/video resolution. Now we have the information inside DB and should take it from DB.

For now inside `dump file` function you can use db_task.video to get access to Video table and db_task.image_set to get access to Image table. Thus you don't need to create video_name field. You can extract all information which you need from DB. If you can as well remove obsolete functions and use DB instead in appropriate place it will be awesome but it is optional.

**Comment by nmanovic** [comment]
@edumotya , let me know what you think. Are you going to adjust your PR request?

**Comment by edumotya** [comment]
I will try it as you suggested @nmanovic

**Comment by edumotya** [comment]
Hi @nmanovic,

Finally I reverted all my previous changes, pulling from develop, and I added a single line into the dump function that extracts the video path from the DB, as suggested. Actually, it was easier. 

For now, I am not removing the obsolete functions, maybe later on...

**Comment by nmanovic** [comment]
@edumotya , thanks! Could you please check your patch? I still can see `db_task.video_name` code in your patch. Do you think we can add something similar for images?

**Comment by edumotya** [comment]
Sorry @nmanovic , you were right... I didn't undo my initial changes. It should be fine now, please check it.
Let me see what we can do for images!

**Comment by edumotya** [comment]
Well, docker-compose build for cvat container has failed... I think it has nothing to do with my commit. Anyway, I will check it later on.

**Comment by nmanovic** [comment]
@edumotya , Thanks for your contribution! Don't hesitate to submit new PRs to improve the tool.

**Pull request merged**
