### PR TITLE
Fix a race condition with initial secret_key.py creation

### PR DESCRIPTION
**Pull request by SpecLad**
### Motivation and context

Currently, it's possible (even if unlikely) for multiple backend processes to create and use different Django `SECRET_KEY` values, because the following scenario can happen:

* process 1: fail to import `secret_key.py`
* process 2: fail to import `secret_key.py`
* process 1: generate a new `secret_key.py`
* process 1: import `secret_key.py`
* process 2: generate a new `secret_key.py`
* process 2: import `secret_key.py`

Fix this by making it so that `secret_key.py` is created atomically, and never overwritten if it already exists.

In addition, only generate the secret key if the import fails due to the module not being found, since other failure reasons suggest incorrect configuration or data corruption, and so require administrator attention.

### How has this been tested?

Manual testing.

### Checklist

- [x] I submit my changes into the `develop` branch
- [x] I have added a description of my changes into the [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
- ~~[ ] I have updated the documentation accordingly~~
- ~~[ ] I have added tests to cover my changes~~
- ~~[ ] I have linked related issues (see [GitHub docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))~~
- ~~[ ] I have increased versions of npm packages if it is necessary
  ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
  [cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning),
  [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and
  [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))~~

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.

### CODE REVIEW

**Comment by nmanovic** [comment]
@SpecLad , let's fix the conflict and simplify the code as discussed. Ping me in slack when it is ready.

**Review by nmanovic — APPROVED** [review]
LGTM

**Comment by Keramblock** [comment]
Hi, @SpecLad @nmanovic , I am not sure, but it is look like that init destoyed new instances for helm chart:
pic

**Comment by Keramblock** [comment]
> @Keramblock Thanks for the report. What filesystem are you using?

that is default azure RWX volume:
изображение
изображение

here is pvc spec:
изображение
изображение

**Comment by Keramblock** [comment]
We dont have NFS server there(and I am not sure if Azure provides production ready NFS storageclass for k8s at all),but is it really necessary to use hardlink here? 

P.S. for now I just copied files from other server and it is working fine

**Pull request merged**
