### PR TITLE
Renamed cvatjs to cvat-core

### PR DESCRIPTION
**Pull request by bsekachev**
* cvatjs => cvat-core
* Updated README.md
* Updated module version

### CODE REVIEW

**Comment by zankevich** [comment]
@bsekachev Can we track `docs` and `dist` folders?

**Comment by bsekachev** [comment]
@zankevich 
What is a reason to store them?

**Comment by zankevich** [comment]
> @zankevich
> What is a reason to store them?

It can be easier for users to have latest docs and dist already in place and not generate them every time library updates.

**Comment by bsekachev** [comment]
@zankevich 
Generation isn't hard in my opinion:
```
cd cvat-core
npm install 
npm run docs
npm run build
```

At the same time we get too much junk info in each PR (these folders size is ~2.2 MB). Furthermore documentation can't be rendered in github. 

Maybe we should generate these files on stable releases, but it is an open question.

**Pull request merged**
