### PR TITLE
[GSoC24] Resolved Issue #7443 (navigate over unresolved issues)

### PR DESCRIPTION
**Pull request by thekavikumar**
Resolved the issue #7443 

### Checklist

- [x] I submit my changes into the `develop` branch
- [x] I have created a changelog fragment 
- [x] I have updated the documentation accordingly
- [x] I have added tests to cover my changes
- [x] I have linked related issues (see [GitHub docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [x] I have increased versions of npm packages if it is necessary
  ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
  [cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning),
  [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and
  [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.

### CODE REVIEW

**Comment by thekavikumar** [comment]
@klakhov can you please review it

**Comment by thekavikumar** [comment]
@nmanovic please review my pr

**Review by klakhov — COMMENTED** [review]
@thekavikumar 
Im not sure you've actually fixed the problem. Your fix just hides resolved issues on the sidebar if the hide setting is enabled. But I still can navigate to the frames with the resolved issues using `find the next frame with issues` buttons.

**Comment by thekavikumar** [comment]
@klakhov alright let me check

**Comment by thekavikumar** [comment]
@klakhov may i know why I'm not able to click on the arrows

image

**Comment by thekavikumar** [comment]
@klakhov how to create new frames?

**Comment by klakhov** [comment]
It seems you have issues created only on the frame you are lookin on. Currenlty there is no possibility to add frames to the job. You need to create correct task.

**Comment by thekavikumar** [comment]
@klakhov can you please guide me how to create correct task

**Comment by thekavikumar** [comment]
@klakhov i mean some example of correct task

**Comment by klakhov** [comment]
Please, refer to the [task creation docs](https://opencv.github.io/cvat/docs/manual/basics/create_an_annotation_task/#select-files). You can select  an archive with multiple images, plain images(e.g several `.jpeg`), or even a video. In any case you will get several frames in the job.

**Comment by thekavikumar** [comment]
@klakhov got it thanks

**Pull request closed without merging**
