### PR TITLE
remove deprecated method call `from_ir`

### PR DESCRIPTION
**Pull request by benhoff**

### CODE REVIEW

**Comment by bsekachev** [comment]
@benhoff 
Hi, thanks for PR. 
Do you happen to know what is the first OpenVINO version which support this API? Probably we should update [README.md file](https://github.com/opencv/cvat/tree/develop/components/openvino#preparation) with it.

**Comment by benhoff** [comment]
https://github.com/opencv/dldt/blame/ba6e22b1b5ee4cbefcc30e8d9493cddb0bb3dfdf/inference-engine/ie_bridges/python/src/openvino/inference_engine/ie_api.pyx#L485

**Comment by benhoff** [comment]
Looks like R5 from 2018

**Comment by bsekachev** [comment]
@benhoff 
Ok, thanks.

**Comment by nmanovic** [comment]
@benhoff , thanks for the contribution. Please give us some time to check the patch. Even it is obvious I would prefer to send some time to test it. I will merge it this week for sure.

**Pull request merged**
