### PR TITLE
Add cancel button to Create a new project/task forms

### LINKED ISSUE #7579: Imporve ux
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://opencv.github.io/cvat/docs/)

### Is your feature request related to a problem? Please describe.

When I created a project the first time and clicked the submit and continue button i was expecting it to create the project and take me back to the projects main page but it didnt and then i searched for a back button which wasnt there.

### Describe the solution you'd like

I would like to either add a back button on the create a new projects page which would take the user back to the main projects page or I would like to redirect the user to the main projects page when they click submit and continue button.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by syedbarimanjan**
### Motivation and context
Fixes #7579 I have added a cancel button to the Create a new project and Create a new task forms which will take the user to the main page of projects/tasks.
Screenshot from 2024-03-13 18-21-15
Screenshot from 2024-03-13 18-21-03

### Checklist

- [x] I submit my changes into the `develop` branch
- [x] I have linked related issues (see [GitHub docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.

### CODE REVIEW

**Comment by bsekachev** [comment]
Hello,

From you use-case:

> When I created a project the first time and clicked the submit and continue button i was expecting it to create the project and take me back to the projects main page but it didnt and then i searched for a back button which wasnt there.


On create project page, what is the difference between "Cancel" button and "Projects" button in the header?

I believe instead of creating buttons we need proper navigation bar, e.g. using Antd breadcrumbs: https://ant.design/components/breadcrumb

**Comment by syedbarimanjan** [comment]
> Hello,
> 
> From you use-case:
> 
> > When I created a project the first time and clicked the submit and continue button i was expecting it to create the project and take me back to the projects main page but it didnt and then i searched for a back button which wasnt there.
> 
> On create project page, what is the difference between "Cancel" button and "Projects" button in the header?
> 
> I believe instead of creating buttons we need proper navigation bar, e.g. using Antd breadcrumbs: https://ant.design/components/breadcrumb

If a user clicks on the 'Projects' button in the navbar, it will navigate them to the main or first page of projects. If the user was on the second or third page, this might result in a less optimal user experience. On the other hand, if the user clicks on the 'Cancel' button, they will be directed back to the page they came from. As for breadcrumbs I think, implementing them might be considered overkill since our project doesn't have a deep hierarchy.

**Comment by bsekachev** [comment]
- I am not sure about the case when user creates a new project from page N and he needs to return to the same page. Why not to open a new browser tab when clicking "Add project" then? 
- Navigation with breadcrumps is not about you project. By contributing to the repository, many users will be affected by these changes. I do not think `Cancel` button provides natural way of navigation, it should be something unified on all the pages (We may also create jobs, cloud storages, ML models).

**Comment by syedbarimanjan** [comment]
> * I am not sure about the case when user creates a new project from page N and he needs to return to the same page. Why not to open a new browser tab when clicking "Add project" then?
> * Navigation with breadcrumps is not about you project. By contributing to the repository, many users will be affected by these changes. I do not think `Cancel` button provides natural way of navigation, it should be something unified on all the pages (We may also create jobs, cloud storages, ML models).



> * I am not sure about the case when user creates a new project from page N and he needs to return to the same page. Why not to open a new browser tab when clicking "Add project" then?
> * Navigation with breadcrumps is not about you project. By contributing to the repository, many users will be affected by these changes. I do not think `Cancel` button provides natural way of navigation, it should be something unified on all the pages (We may also create jobs, cloud storages, ML models).

I have encountered situations where I am low on RAM because the project consumes a significant amount of it. Opening a new tab exacerbates the issue. When I refer to 'our project,' I am specifically talking about the CVAT project. Now, as I navigate through all the pages, I believe that the navigation system needs improvement, and implementing breadcrumbs could enhance it and I will work on it.

> (We may also create jobs, cloud storages, ML models) 
I dont understand what you are trying to say here.

**Comment by syedbarimanjan** [comment]
> Problem is more common then just getting back from `Create task/project page`. And, I agree that such solution may be quite complex to implement, but that is not a reason to implement "temporary" solutions as "Cancel" button.

As I was new to the project and hadnt used it for long so I didnt understand that the problem was common and thus the Cancel button didnt seem as a temporary solution. Implementing breadcrumbs isnt that complex to implement.

**Comment by syedbarimanjan** [comment]
Screenshot from 2024-03-14 00-39-39
I like the first one

**Comment by syedbarimanjan** [comment]
We will add breadcrumbs to all pages as is seen in other web apps?

If yes then we should decide on where should they be located.

If we implement breadcrumbs then we will remove the buttons like these?
Screenshot from 2024-03-14 01-02-05
the back button here
Screenshot from 2024-03-14 01-03-56
the cancel button here

**Comment by bsekachev** [comment]
Hello,

> We will add breadcrumbs to all pages as is seen in other web apps? If yes then we should decide on where should they be located.

I think yes. Maybe except for annotation view, because there are a lot of elements. Sure, we need a design first before development. 

> If we implement breadcrumbs then we will remove the buttons like these?

Yes. 

> I have encountered situations where I am low on RAM because the project consumes a significant amount of it.

This is about performance. How much is significant amount? If you believe there are problems, need to investigate them, but we need more details. I know only annotation view may consume RAM to store decoded images in some amount and annotations. On other views it should not be a problem now. 

> I dont understand what you are trying to say here.

I meant that we may create other resources. But you proposed to add `Cancel` button to Project and Task only. 

Also, IMHO, 3 buttons is too much in bottom of the forms

**Comment by syedbarimanjan** [comment]
> Hello,
> 
> > We will add breadcrumbs to all pages as is seen in other web apps? If yes then we should decide on where should they be located.
> 
> I think yes. Maybe except for annotation view, because there are a lot of elements. Sure, we need a design first before development.
> 
> > If we implement breadcrumbs then we will remove the buttons like these?
> 
> Yes.
> 
> > I have encountered situations where I am low on RAM because the project consumes a significant amount of it.
> 
> This is about performance. How much is significant amount? If you believe there are problems, need to investigate them, but we need more details. I know only annotation view may consume RAM to store decoded images in some amount and annotations. On other views it should not be a problem now.
> 
> > I dont understand what you are trying to say here.
> 
> I meant that we may create other resources. But you proposed to add `Cancel` button to Project and Task only.
> 
> Also, IMHO, 3 buttons is too much in bottom of the forms

So does the project have a ui designer who will design it?
Does the project have a figma file which has all of the ui made so we can design init? If not should we make one as it will be helpful I am quite proficient with figma?

**Comment by bsekachev** [comment]
Unfortunately, I do not think that sharing Figma project to 3rdparty contributors is possible :(

**Comment by syedbarimanjan** [comment]
> Unfortunately, I do not think that sharing Figma project to 3rdparty contributors is possible :(

So you will design it and send me the Pictures or should I just start it?

Having a proper design will help alot.

**Comment by bsekachev** [comment]
That is out of current scope for us. Let's postpone this modification.

**Comment by syedbarimanjan** [comment]
> That is out of current scope for us. Let's postpone this modification.

Ok.

**Pull request closed without merging**
