### PR TITLE
Fix debug configurations for vs code

### PR DESCRIPTION
**Pull request by zhiltsov-max**
### Motivation and context

- Fixed naming and added a missing debug config for rq workers

### Checklist

- [ ] I submit my changes into the `develop` branch
- [ ] I have added a description of my changes into the [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] I have linked related issues (see [GitHub docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [ ] I have increased versions of npm packages if it is necessary
  ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
  [cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning),
  [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and
  [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))

### License

- [ ] I submit _my code changes_ under the same [MIT License](
  https://github.com/opencv/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.

### CODE REVIEW

**Comment by MustiDarsh** [comment]
Is it possible to address the issue of https://github.com/opencv/cvat/issues/5675 in this PR as well?

**Comment by zhiltsov-max** [comment]
@MustiDarsh, hi. Probably, no. I've encountered the problem, is seems VS code-related.

**Comment by MustiDarsh** [comment]
@zhiltsov-max Thanks for you reply. Has it worked in the past and does it work for others (to your knowledge)?

**Comment by zhiltsov-max** [comment]
@bsekachev, could you please look at #5675?

**Review by nmanovic — APPROVED** [review]

**Pull request merged**
