### PR TITLE
Fix: Can't dump annotations with objects type is track from several jobs

### LINKED ISSUE #3200: [Bug] Can't dump annotations with objects type is track from several jobs (annotation is created in all job).
### My actions before raising this issue
- [ ] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ ] Searched [past issues](/issues)

### Expected Behaviour
1) response_code == 202
2) file was downloaded 

### Current Behaviour
Can't dump and raise ValueError: Unknown internal frame id 10.
It seems that CVAT incorrectly merges job annotations because the task has an annotation with frame 10 and 11 in database after creation of annotations in all jobs.

### Steps to Reproduce (for bugs)
1) create task with several jobs:
  - 10 images
  - 3 overlap size
  - 6 segment size
2) create rectangle/polygon/polylines/points (track) annotations in jobs
3) dump CVAT for images 1.1 annotations
(GET query /api/v1/tasks/1/annotations&format=CVAT for video 1.1)

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

### PR DESCRIPTION
**Pull request by yasakova-anastasia**
### Motivation and context

Fixed #3200

### Checklist

- [x] I submit my changes into the `develop` branch
- [x] I have added a description of my changes into [CHANGELOG](https://github.com/cvat-ai/cvat/blob/develop/CHANGELOG.md) file
- [ ] I have updated the [documentation](
  https://github.com/cvat-ai/cvat/blob/develop/README.md#documentation) accordingly
- [x] I have added tests to cover my changes
- [x] I have linked related issues ([read github docs](
  https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
- [ ] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/cvat-ai/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/cvat-ai/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/cvat-ai/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/cvat-ai/cvat/tree/develop/cvat-ui#versioning))

### License

- [x] I submit _my code changes_ under the same [MIT License](
  https://github.com/cvat-ai/cvat/blob/develop/LICENSE) that covers the project.
  Feel free to contact the maintainers if that's a concern.

### CODE REVIEW

**Comment by zhiltsov-max** [comment]
The export seems to be working. However, I failed to import the exported back.

[task_test_3200_backup_2022_11_07_17_58_38.zip](https://github.com/opencv/cvat/files/9954346/task_test_3200_backup_2022_11_07_17_58_38.zip)
[task_test_3200-2022_11_07_17_58_38-cvat for video 1.1.zip](https://github.com/opencv/cvat/files/9954357/task_test_3200-2022_11_07_17_58_38-cvat.for.video.1.1.zip)

```
 File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/django/cvat/apps/dataset_manager/task.py", line 775, in import_task_annotations
    task.import_annotations(f, importer, conv_mask_to_poly=conv_mask_to_poly)
  File "/home/django/cvat/apps/dataset_manager/task.py", line 660, in import_annotations
    self.create(task_data.data.serialize())
  File "/home/django/cvat/apps/dataset_manager/task.py", line 617, in create
    self._patch_data(data, PatchAction.CREATE)
  File "/home/django/cvat/apps/dataset_manager/task.py", line 607, in _patch_data
    self._merge_data(_data, jobs[jid]["start"], self.db_task.overlap)
  File "/home/django/cvat/apps/dataset_manager/task.py", line 611, in _merge_data
    annotation_manager.merge(data, start_frame, overlap)
  File "/home/django/cvat/apps/dataset_manager/annotation.py", line 158, in merge
    tracks.merge(data.tracks, start_frame, overlap)
  File "/home/django/cvat/apps/dataset_manager/annotation.py", line 241, in merge
    cost_matrix[i][j] = 1 - self._calc_objects_similarity(
  File "/home/django/cvat/apps/dataset_manager/annotation.py", line 414, in _calc_objects_similarity
    obj1_shapes = TrackManager.get_interpolated_shapes(obj1, start_frame, end_frame)
  File "/home/django/cvat/apps/dataset_manager/annotation.py", line 758, in get_interpolated_shapes
    if not prev_shape["outside"]:
KeyError: 'outside'
```

**Comment by zhiltsov-max** [comment]
The annotation import seem to be working. However, I failed to import the exported task as a dataset into an empty project.

```
    project.import_dataset(f, importer, conv_mask_to_poly=conv_mask_to_poly)
  File "/cvat/apps/dataset_manager/project.py", line 146, in import_dataset
    self.create({tid: ir.serialize() for tid, ir in self.annotation_irs.items() if tid in project_data.new_tasks})
  File "/cvat/apps/dataset_manager/project.py", line 54, in create
    self.task_annotations[task_id].create(data)
  File "/cvat/apps/dataset_manager/task.py", line 626, in create
    self._patch_data(data, PatchAction.CREATE)
  File "/cvat/apps/dataset_manager/task.py", line 606, in _patch_data
    splitted_data[jid] = _data.slice(start, stop)
  File "/cvat/apps/dataset_manager/annotation.py", line 133, in slice
    track = self._slice_track(t, start, stop)
  File "/cvat/apps/dataset_manager/annotation.py", line 101, in _slice_track
    interpolated_shapes = TrackManager.get_interpolated_shapes(
  File "/cvat/apps/dataset_manager/annotation.py", line 751, in get_interpolated_shapes
    assert shape["frame"] > prev_shape["frame"]
```

[task_test_3200-2022_11_13_09_23_21-cvat for video 1.1.zip](https://github.com/opencv/cvat/files/9996893/task_test_3200-2022_11_13_09_23_21-cvat.for.video.1.1.zip)

**Comment by yasakova-anastasia** [comment]
> The annotation import seem to be working. However, I failed to import the exported task as a dataset into an empty project.

 Fixed.

> Also, something about backup import looks broken, but I can't say what it is exactly. I removed the task from the first testing and can't compare. I feel like I was annotating a bit differently, but having tested it now, I don't see errors.

I think there is a problem on the UI. `overlap > 0` in the task, so when annotations are added to one job, it must be added to the corresponding frames of another job. This is not happening.

**Review by zhiltsov-max — APPROVED** [review]

**Review by nmanovic — APPROVED** [review]

**Comment by zhouxiao999** [comment]
I still have this problem with the latest version test today.
A video is divided into multiple jobs. If several jobs contain track：
1. Export task  as a dataset  with video 1.1 （images 1.1 is ok，no such problem）
2. upload anotation without modifying it，the system displays "Error: Request failed with status code 500. "KeyError: 'type'\n"

**Pull request merged**
