### PR TITLE
React UI: Pinned option was added

### PR DESCRIPTION
**Pull request by bsekachev**
* Enabled by default for all polyshapes
* Pinned shapes cannot be moved (resize, changing attributes, etc. work as usual)
* Undo/redo support

Screenshot from 2020-02-26 18-11-41

### CODE REVIEW

**Comment by nmanovic** [comment]
@ActiveChooN , please review and try the patch.

**Comment by bsekachev** [comment]
@ActiveChooN 

Resolved merge conflicts. Need review again

**Comment by ActiveChooN** [comment]
Is this action suitable for points? Maybe it can be useful to hide this button for points object item menu.
image

**Comment by bsekachev** [comment]
@ActiveChooN 

Yes, I agree. 
Done.

**Comment by kgloveyou** [comment]
How to pin points?

**Pull request merged**
